### ISSUE TITLE
opencl float atomics

### ISSUE THREAD

**Issue by dshawul** [libocca/occa#1]
I am in need of atomicAdd for floats in OCCA. Currently it seems only CUDA atomicAdd on floats work. AtomicAdd on doubles doesn't work in CUDA, and OpenCL does not seem to define it on floats/doubles at all. I know CUDA doesn't implement atomicAdd on 64 bit directly but via atomicCAS, but it would be great to have it.

My OpenCL is:

  Version:                   OpenCL 1.2 AMD-APP (1445.5)
  Extensions:                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_amd_svm cl_khr_gl_event

**Comment by dmed256** [comment]
Hi Daniel,

I'm on a road trip but I'll try to add it this week

**Comment by dshawul** [comment]
Ok, thanks for your great work!

**Comment by dmed256** [comment]
Hi Daniel,

Just got back earlier today (ehh .. I guess it's yesterday by now)

I'm going to start working on atomics this weekend, I'll aim to get it to you before Monday

Just to make sure, float + double atomics and general-purpose atomics:

    occaAtomicLock(ptr); // ptr is hashed to get a lock (faster than having just one lock)
    // Work
    occaAtomicUnlock(ptr);

Is there any other atomic-like feature that would be useful?

Thanks,
David

**Comment by dshawul** [comment]
Hi David, 
Welcome back. What I need most is atomicAdd (float/double versions), which I have so far managed to avoid  using coloring techniques and such. It is easier/lazier to just be able to use atomicAdd instead. We may need locks at some point so those would be great too.
regards,
Daniel
