### ISSUE TITLE
Use proper locks when compiling kernels

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#101]
As mentioned in https://github.com/CEED/libCEED/issues/49#issue-309428205, the `SIGKILL` case isn't covered when locking files. Use a proper file locking system that still works in a NFS.

Check out `fcntl`

**Comment by pdhahn** [comment]
Yes SIGKILL cannot be blocked nor handled in a recoverable way by means of the signal API mechanisms, but ^C should normally generate a SIGINT, which _can_ be blocked/handled.

Nevertheless, I agree this issue with atomicity should best be rectified by means of a transaction (as mentioned in the **CEED** comment referenced above), not a global critical section based on file locks.

The critical section approach could be susceptible to corruption with a random SIGKILL, even though it can be made immune to SIGTERM / SIGINT / ^C. In contrast, the transaction approach would be safe with SIGKILL.

Moreover, easing portability to non-*nix systems such as native Windows is another good reason to use the transaction approach.

**Comment by dmed256** [comment]
Added staleness check in 9fb79c6810503b6028f3d77328190fdca75d0a91
