### ISSUE TITLE
File not found: 'sys/sysinfo.h' on macOS Sierra 10.12.6 

### ISSUE THREAD

**Issue by v-dobrev** [libocca/occa#102]
The error comes from this line:

https://github.com/libocca/occa/blob/a4e49f2efaa828b33a926964ebba24a84c482c6b/src/tools/sys.cpp#L34

I have XCode 8.3.3 - not sure if that matters.

**Comment by dmed256** [comment]
Oops, sneaked in 8baa50de8c068c2d9662fba0dff292cb51fce8d5 
Fixed in 6131fc55c1e9ddf287832d3b762fa8ba4a9fcc5b, thanks!
