### ISSUE TITLE
Suggestions for Fortran API

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#104]
It would be nice to revive the Fortran API found in the (libocca/occa-fortran)[https://github.com/libocca/occa-fortran] repo

Unfortunately I'm a Fortran noob, so I'm looking for suggestions on how to make the Fortran API look nice and mirror the C API (or cleaner if we can!). Questions include:

- Should we aim for F77 or a newer version?
- How does `NULL` work in Fortran? (we use it for some defaults)
- How do we wrap the `occaInt`, `occaDouble`, ... C objects?

**Comment by nicholasmalaya** [comment]
* I'm a huge fan of SWIG, and could help provide an example. This is an easy way to generate interfaces to a vast multitude of languages, more than 'just' fortran. Would introduce a dependency into OCCA but it could be made command line optional. 
* F2003 is probably best, but F90 should be considered 'minimal'. F77 is prehistoric.
* F2003 does have a concept of a NULL pointer, but I don't know if that can be passed, C-like

Just my two cents. Great idea!

-NM

**Comment by dmed256** [comment]
I would prefer we tailor the APIs based on the language, but I can take a look at SWIG to start with!

If no one else complains about F2003 being too 'new', I'll aim for that once I (or someone else) starts the Fortain API

**Comment by pdhahn** [comment]
I suppose my minimum recommendation would be f95. This keeps the parser challenges manageable while accommodating what I believe are the interests of most Fortran programmers still actively developing or maintaining(!) code in various application domains where Fortran was/is the language of choice. Writing a parser for f2003 might be more time-consuming and not worth the extra effort if the vast majority of legacy Fortran code still being used, maintained and suitable for _OCCA-izing_ does not require it.

On the other hand, if OCCA can parse f2003 /f2008, then that would be a very good reason for coders to (re)write code using f2003/f2008 features moving forward. :-)

As for SWIG, per their site page: "SWIG is typically used to parse C/C++ interfaces and generate the 'glue code' required for the above target languages to call into the C/C++ code." I did not see Fortran in the list of languages(?).

**Comment by dmed256** [comment]
@pdhahn This is for the API, not for a Fortran Kernel Language (like OFL in the past)

**Comment by pdhahn** [comment]
Oops, sorry for missing the point (yes I was thinking a revival of "OFL" was in the offing for 1.0)!

**Comment by dmed256** [comment]
np, thought that counts :)

**Comment by dmed256** [comment]
@awehrfritz suggested + implemented the full thing! Closed by #341
