### ISSUE TITLE
[FORTRAN] unnecessary printf statements

### ISSUE THREAD

**Issue by dshawul** [libocca/occa#11]
Unnecessary printf statement

 src/FC.cpp line 10 -    printf("type = %p\n", *type);

Also when occa is run  with thousands of GPUs, the info message for cached kernel becomes too much, so I suggest an option to turn it on/off.

//std::cout << "Found cached binary of [" << compressFilename(filename) << "] in [" << compressFilename(binaryFile) << "]\n";

regards,
Daniel

**Comment by dmed256** [comment]
You can turn it off with
   occa::setVerboseCompilatiob(false)

**Comment by dmed256** [comment]
Compilation* (typing on phone)

**Comment by dmed256** [comment]
In Fortran it's occaSetVerboseCompilation(.FALSE.)

**Comment by dmed256** [comment]
And removed the debugging printf
Thanks!

**Comment by dshawul** [comment]
Thanks David!

**Comment by dmed256** [comment]
No problem =)
