### ISSUE TITLE
unroll pragma bug

### ISSUE THREAD

**Issue by jkozdon** [libocca/occa#12]
To work with intel compilers, I think that https://github.com/libocca/occa/blob/master/include/occa/defines/OpenMP.hpp#L437
```
#define occaUnroll(N)  occaUnroll2(unroll N)
```
should be
```
#define occaUnroll(N)  occaUnroll2(unroll(N))
```

**Comment by dmed256** [comment]
Just pushed the changes (it's only for the Intel compiler)
