### ISSUE TITLE
indexing failure using exclusive variables 

### ISSUE THREAD

**Issue by jlchan** [libocca/occa#143]
Indexing fails using 1.0 exclusive variables.  For example, for a code snippet like

@exclusive int ii,jj;
... <code block> ...
ii = i % 4;
jj = i / 4;
... <code block> ...
s_D[ii][jj] = D1D[i];

I get an error message 

/Users/jchan985/.occa/cache/b3f287c0b280cbaa/source.cpp:109:10: error: array subscript is not an integer

      s_D[ii][jj] = D1D[i];

**Comment by dmed256** [comment]
Fixed in 51d0963
