### ISSUE TITLE
shared mem barrier issue 

### ISSUE THREAD

**Issue by jlchan** [libocca/occa#147]
Barriers behave oddly?  The code below fills a shared 2-element array, barriers, and then tries to access both elements on each thread.  The answer should be the same across all threads.  

I'm running on a K80 using CUDA 9.0 on Ubuntu 16.04 (Google Cloud Platform).

```
@kernel void testShared(const int entries){
  for (int i = 0; i < 1; ++i; @outer){
    @shared float s_a[2];
    for (int j = 0; j < 4; ++j; @inner){
      if (j < 2){
        s_a[j] = 1.f + (float) j;
      }
    }
    @barrier("localMemFence");
    for (int j = 0; j < 4; ++j; @inner){
      printf("i,j = %d, %d: s_a[0,1] = %f,%f\n",
             i,j,s_a[0],s_a[1]);
    }
  }
}

```

>     ========+======================+================================
>      CPU(s) | Processor Name       | Intel(R) Xeon(R) CPU @ 2.30GHz 
>             | Cores                | 1                              
>             | Memory (RAM)         | 3.60 GB                        
>             | Clock Frequency      | 2.3 GHz                        
>             | SIMD Instruction Set | SSE2                           
>             | SIMD Width           | 128 bits                       
>             | L1 Cache Size (d)    |    32K                         
>             | L2 Cache Size        |   256K                         
>             | L3 Cache Size        | 46080K                         
>     ========+======================+================================
>      OpenCL | Device Name          | Tesla K80                      
>             | Driver Vendor        | NVIDIA                         
>             | Platform ID          | 0                              
>             | Device ID            | 0                              
>             | Memory               | 11.17 GB                       
>     ========+======================+================================
>      CUDA   | Device ID            | 0                              
>             | Device Name          | Tesla K80                      
>             | Memory               | 11.17 GB                       
>     ========+======================+================================
> i,j = 0, 0: s_a[0,1] = 1.000000,0.000000
> i,j = 0, 1: s_a[0,1] = 0.000000,2.000000
> i,j = 0, 2: s_a[0,1] = 0.000000,0.000000
> i,j = 0, 3: s_a[0,1] = 0.000000,0.000000

**Comment by dmed256** [comment]
Seems `@shared` isn't expanding properly, I'll look into it!

```cpp

extern "C" __global__ void testShared_0(const int entries) {
  {
    int i = 0 + blockIdx.x;
    float s_a[2];
    {
      int j = 0 + threadIdx.x;
      if (j < 2) {
        s_a[j] = 1.00000000e+00f + (float) j;
      }
    }
     __syncthreads();
    {
      int j = 0 + threadIdx.x;
      printf("i,j = %d, %d: s_a[0,1] = %f,%f\n", i, j, s_a[0], s_a[1]);
    }
  }
}
```
