### ISSUE TITLE
occa translate

### ISSUE THREAD

**Issue by jlchan** [libocca/occa#150]
The occa translate option is nice, but it'd be more useful if it could handle parameters which aren't defined in the .okl file.  It's tougher to use on more complex kernels.

**Comment by pdhahn** [comment]
Question: Although anachronistic for OCCA v1.0, I have an `occac` program in my 0.2-based application space that allows me to compile kernels on the command line, albeit usually not for production, rather for syntax checks. It takes `-I <include-file-path>`, `-D<name>`  and `-D<name>=<value>` options on the command line. Is something like the -I and -D options what you are talking about but in terms of the new occa "`translate`" (and "`compile`") command in this issue? Note I've not tried the new `translate` or `compile` commands yet myself, just wondering.

**Comment by dmed256** [comment]
There is a `-k` (or `--kernel-props`) option

```bash
> occa translate --help

Usage: occa translate [OPTIONS] FILE [FILE...]

Translate kernels

Arguments:
  FILE    An .okl file

Options:
  -k, --kernel-props    Kernel properties
  -m, --mode            Output mode
```

I'll make another issue regarding simpler flags like `-I` and `-D`
