### ISSUE TITLE
Loopy removal

### ISSUE THREAD

**Issue by inducer** [libocca/occa#16]
Regarding 96d9460ccf41:

I'm wondering about the right path forward here. Sure, I can call loopy myself using whatever syscall, and that's essentially equivalent to the code that was removed. But since loopy can take a couple seconds to run, the right thing to do would be to cache its output. I was rather hoping to piggyback off of OCCA's compiler cache to do so, which would point in the direction of tighter integration. So what I'm looking for here is a pronouncement by either @tcew or @dmed256 along one of the following lines:

* There will be no loopy-anything in occa. Third-party toolchain components will not be supported as part of OCCA, in particular with respect to cache integration.
* There will be no loopy-anything in occa. Third-party toolchain components are a possiblity.
* Loopy as part of the build chain is welcome back into occa, as long as conditions XYZ are met.

cc @lcw

**Comment by lcw** [comment]
I think a possible way forward would be (if possible) to figure out the
right abstraction so that loopy and other third-party toolchains can
be "plugged into occa".  Moving the loopy specific bits to the
application.

**Comment by dmed256** [comment]
I think making OCCA accessible to 3rd-party applications is definitely good, but I don't want to include them in the OCCA repo because they don't belong there. There is already
```
occa::getFileContentHash(filename, salt)
occa::getContentHash(fileContents, salt)
occa::fileExists(filename)
occa::getFilename(filename)
```
that will do the job for you

For example, if you want to store all the loopy kernels you can do:
```
std::string hash = occa::getFileContentHash("myKernel.loopy", <loopy_options>)
std::string clFilename = occa::getFilename("[loopy]/myKernel_" + hash + ".cl")
if(occa::fileExists(clFilename)){
   <use loopy to generate clFilename>
}
occa::buildKernel(clFilename)
```
where "[loopy]/myKernel..." is OCCA notation for "stick it in OCCA cache path in a directory called 'loopy'"

**Comment by dmed256** [comment]
To make the [loopy] directory for [loopy]/myKernel_....:
```
occa::sys::mkpath(occa::getFileDirectory(clFIlename))
```

**Comment by dmed256** [comment]
Eh, just to be clear, I literally mean put "[loopy]/myKernel.cl"
Here's an example where I use it in OCCA:
    https://github.com/libocca/occa/blob/master/src/tools.cpp#L1086

**Comment by inducer** [comment]
How about cache locking/unlocking/storing/retrieving?

**Comment by dmed256** [comment]
```
if(!occa::haveHash(hash)){
    occa::waitForHash(hash);
}
else {
    <use loopy to generate clFilename>
    occa::releaseHash(hash);
}
```

**Comment by dmed256** [comment]
@inducer Anything else needed?

**Comment by inducer** [comment]
Thanks for the hints. I'll let you know if we need anything else.
