### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [libocca/occa#176]
Would you like to [replace any double quotes](https://github.com/libocca/occa/blob/a6521ea75665ae4c1f00de928e5c4b9d1c437ac0/include/occa.h#L22 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by dmed256** [comment]
Oops, must have missed them during f8550c70d3a5d1bd8fc6f44e063f949e1da428b7
Pushed in 1161e0a927d0e0b9a108c9da49913a126bdc3289, will push to master soon-ish
