### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [libocca/occa#177]
I suggest to reuse a higher level build system than [your current make script](https://github.com/libocca/occa/blob/56ddc819767021ebf5256a5dbc16d16e534207eb/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by dmed256** [comment]
I've struggled on that one a bit, but I think I'll stick with plain old `make` for now
I like being able to `git clone` + `make` for easy installation (sometimes machines don't come with `cmake` or `autotools`)

If it becomes an issue over time, I'll reconsider updating the installation method, thanks for the feedback!

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.12/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by elfring** [comment]
* Are you looking for possibilities around safer dependency management with involved software components?
* Would you dare another look besides the glance?

**Comment by pdhahn** [comment]
@elfring Just wondering what are the issues you are experiencing with the current OCCA build system that would motivate adoption of something totally different (i.e., not based on `make`)?

**Comment by elfring** [comment]
I am used to advanced functionality from the mentioned build tools.
How do you view the corresponding software situation?

**Comment by pdhahn** [comment]
I agree with @dmed256 that keeping it simple right now is best, which means stick with `make`.

I asked the question because I am wondering if you are actually having real issues (e.g., portability) with the current make system. If so, please report those to @dmed256 in detail so he can address them. I believe there is already another issue open about improvements to the make system, too, so he is already aware that some changes are needed.

**Comment by elfring** [comment]
Can you get portability concerns from variations of the tool “`make`”?

**Comment by pdhahn** [comment]
Yes most definitely.

**Comment by elfring** [comment]
Can other build tools help any more to tackle related software development challenges?

**Comment by pdhahn** [comment]
But they can all be addressed, especially if you stick with GNU gmake.

IMO, further considerations are not very relevant to OCCA at this point.
