### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [libocca/occa#178]
How do you think about to benefit from [parallel build trees](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html "Parallel build trees (a.k.a. VPATH builds)") also for this software?
Would you like to [support out-of-source](https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build "https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build") ([VPATH](https://www.gnu.org/software/make/manual/html_node/General-Search.html "Search path for all prerequisites")) builds?

**Comment by dmed256** [comment]
I believe we're already doing this since we build `.o` objects in the `obj/` directory that shadows the `src/` directory. 

One missing feature, which we have to tackle at some point, is to install given a `$PREFIX` or `--prefix` (if it's done through a CLI like `occa`)

**Comment by elfring** [comment]
Did you read any of the linked information sources for the usage of parallel build trees (out-of-source builds)?

**Comment by dmed256** [comment]
Yes.

**Comment by dmed256** [comment]
@elfring I appreciate the feedback about the build system, but I don't think I have much time to spend on updating it at the moment

**Comment by elfring** [comment]
Should the mentioned subdirectory “`obj`” be stored then in an other data output folder which is separate from the source location?
