### ISSUE TITLE
Let the device create the kernel hash

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#184]
Currently all kernel properties are used to generate its hash
In reality, it only needs

- General properties
  - `defines`
  - `includes`
  - `header`
  - `include_paths`
- Backend specific properties, such as
  - `compiler`
  - `compilerFlags`

Things that shouldn't be used are `verbose` for example

**Comment by tcew** [comment]
Ideally the contents of the headers should be hashed too.

**Comment by dmed256** [comment]
Moved the dependencies part to #203
