### ISSUE TITLE
CUDA multiple defines

### ISSUE THREAD

**Issue by jkozdon** [libocca/occa#19]
When I run example `occa/examples/addVectors/c/`  in cuda mode I get a bunch of multiple define warnings between `primitives.hpp` and `CUDA.hpp` as well as `defines.hpp`

There is also an error from an unfound file: occa/defines.hpp

**Comment by jkozdon** [comment]
Here is my relevant output.

```
Compiling [addVectors0]
nvcc  -arch=sm_35  -Xptxas -v,-dlcm=cg,-abi=no  -x cu -c /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa -o /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/ptxBinary.o
In file included from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:2:
/home/jekozdon/._occa/libraries/occa/primitives.hpp:12:30: error: occa/defines.hpp: No such file or directory
nvcc -o /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/binary -ptx -I. -I/home/jekozdon/codes/occa//include  -arch=sm_35   -x cu /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa
In file included from /home/jekozdon/._occa/libraries/occa/primitives.hpp:12,
                 from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:2:
/home/jekozdon/codes/occa//include/occa/defines.hpp:146:1: warning: "OCCA_COMPILED_WITH" redefined
In file included from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:1:
/home/jekozdon/._occa/libraries/occa/defines/CUDA.hpp:30:1: warning: this is the location of the previous definition
In file included from /home/jekozdon/._occa/libraries/occa/primitives.hpp:12,
                 from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:2:
/home/jekozdon/codes/occa//include/occa/defines.hpp:217:1: warning: "OCCA_SSE2" redefined
In file included from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:1:
/home/jekozdon/._occa/libraries/occa/defines/CUDA.hpp:40:1: warning: this is the location of the previous definition
In file included from /home/jekozdon/._occa/libraries/occa/primitives.hpp:12,
                 from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:2:
/home/jekozdon/codes/occa//include/occa/defines.hpp:223:1: warning: "OCCA_SSE" redefined
In file included from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:1:
/home/jekozdon/._occa/libraries/occa/defines/CUDA.hpp:41:1: warning: this is the location of the previous definition
In file included from /home/jekozdon/._occa/libraries/occa/primitives.hpp:12,
                 from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:2:
/home/jekozdon/codes/occa//include/occa/defines.hpp:229:1: warning: "OCCA_MMX" redefined
In file included from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:1:
/home/jekozdon/._occa/libraries/occa/defines/CUDA.hpp:42:1: warning: this is the location of the previous definition
In file included from /home/jekozdon/._occa/libraries/occa/primitives.hpp:12,
                 from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:2:
/home/jekozdon/codes/occa//include/occa/defines.hpp:245:1: warning: "OCCA_VECTOR_SET" redefined
In file included from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:1:
/home/jekozdon/._occa/libraries/occa/defines/CUDA.hpp:44:1: warning: this is the location of the previous definition
In file included from /home/jekozdon/._occa/libraries/occa/primitives.hpp:12,
                 from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:2:
/home/jekozdon/codes/occa//include/occa/defines.hpp:259:1: warning: "OCCA_SIMD_WIDTH" redefined
In file included from /home/jekozdon/._occa/kernels/b2ed1772c9f4490c/source.occa:1:
/home/jekozdon/._occa/libraries/occa/defines/CUDA.hpp:46:1: warning: this is the location of the previous definition
```

**Comment by lcw** [comment]
Hi @jkozdon,

I think that #24 will fix these issues.  If you get a chance, can you please give it a try?

**Comment by tcew** [comment]
The fix worked for me.

On Wed, Jan 20, 2016 at 4:21 PM, Lucas C Wilcox <notifications@github.com>
wrote:

> Hi @jkozdon <https://github.com/jkozdon>,
>
> I think that #24 <https://github.com/libocca/occa/pull/24> will fix these
> issues. If you get a chance, can you please give it a try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libocca/occa/issues/19#issuecomment-173362718>.
>



-- 
/*

Tim Warburton
John K. Costain Faculty Chair in the College of Science
Professor of Mathematics
Affiliated Faculty in the Computational Modeling and Data Analytics Program
Virginia Tech

+1 540 231 8274
http://tcew.github.io

*/

**Comment by axmodave** [comment]
This works for me too. There is no warning when compiling kernels with CUDA.

On Wed, Jan 20, 2016 at 3:38 PM, Tim Warburton <notifications@github.com>
wrote:

> The fix worked for me.
>
> On Wed, Jan 20, 2016 at 4:21 PM, Lucas C Wilcox <notifications@github.com>
> wrote:
>
> > Hi @jkozdon <https://github.com/jkozdon>,
> >
> > I think that #24 <https://github.com/libocca/occa/pull/24> will fix
> these
> > issues. If you get a chance, can you please give it a try?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/libocca/occa/issues/19#issuecomment-173362718>.
> >
>
>
>
> --
> /*
>
> Tim Warburton
> John K. Costain Faculty Chair in the College of Science
> Professor of Mathematics
> Affiliated Faculty in the Computational Modeling and Data Analytics Program
> Virginia Tech
>
> +1 540 231 8274
> http://tcew.github.io
>
> */
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libocca/occa/issues/19#issuecomment-173367968>.
>



-- 
Dr Axel MODAVE
Postdoctoral Associate
Virginia Tech

http://www.axel.modave.eu/
http://tcew.github.io/

**Comment by jkozdon** [comment]
Works for me.
