### ISSUE TITLE
Properly handle undefineds in preoprocessor #if's

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#190]
In v0.2, I have trouble using preprocessor conditionals involving expressions with undefined constants, like  `#if MY_DEFN > 0`, where `MY_DEFN` has not have been defined beforehand via a `#define`. These seem to not work. I have to stick with using `#ifdef` and `#ifndef`, like `#ifdef MY_DEFN`. I am not sure about the status of this kind of thing in v1.x, but assuming the behavior is currently the same as in v0.2, it would be helpful if `#if` expressions like this were made to work.

Note the C99 standard preprocessor will interpret a reference name such as `MY_DEFN` in `#if MY_DEFN > 0`  to have the value 0 when it has not been defined.

**Comment by pdhahn** [comment]
To be more clear, in v0.2, the code inside` #if MY_DEFN > 0 ... #endif` gets parsed when `MY_DEFN` is undefined, although it should not in that case.

**Comment by dmed256** [comment]
Fixed in 5bf34fa66508f8c2210fc1daa762c3b17d8c716a
Thanks!
