### ISSUE TITLE
Avoid repeated memory allocation/deallocation in occa::linalg::dot

### ISSUE THREAD

**Issue by v-dobrev** [libocca/occa#192]
The following memory allocation (and subsequent deallocation at the end of the function) seems to be a bottleneck (at least in CUDA mode):
https://github.com/libocca/occa/blob/40cfccb501983d62e092ba85ec0580536dc332c8/include/occa/array/linalg.tpp#L336
One solution could be to lazy-allocate (or pre-allocate) the buffer making it a member of the device object.

**Comment by dmed256** [comment]
The reason it was removed was because the memory was not being freed causing memory leaks. The work on #185 should let us add it again without memory leak worries

Thanks for the bug report!

**Comment by pdhahn** [comment]
First of all, I would respectfully assert it is not really a good idea to provide the `libalg` functions as "built-in". Maybe they should be placed under examples or be in some kind of separate library.

Next, if the idea of a "reduction buffer" is to facilitate OCCA support for reductions like OpenMP provides (with `parallal for`), then I believe that its scope cannot be device-wide, but has to exist only within the context of the loop construct involved (e.g., the specific `parallel for`).

**Comment by dmed256** [comment]
Hopefully fixed in 527494c949e95451f491c710592e9cd91e52b56f, will merge to master once CI tests pass

**Comment by v-dobrev** [comment]
Thanks, @dmed256!
