### ISSUE TITLE
libCEED Travis CI With OCCA Now Failing

### ISSUE THREAD

**Issue by jeremylt** [libocca/occa#198]
A recent update to OCCA now gives a failure in Travis for OCCA for all examples, CEED, MFEM, and PETSc. I suspect there is a change that needs to get updated in our OCCA backends

PR Link with failing Travis:
https://github.com/CEED/libCEED/pull/143

**Comment by jeremylt** [comment]
This commit works with libCEED

https://github.com/libocca/occa/commit/527494c949e95451f491c710592e9cd91e52b56f

**Comment by dmed256** [comment]
My bad, accidentally pushed a bad commit to master

**Comment by jeremylt** [comment]
No worries. I just wanted to make sure you knew because it could have been something we needed to adjust on our end.

**Comment by jeremylt** [comment]
I'm still seeing the issue. I made a PR for libCEED that runs Travis against the last version of OCCA that libCEED passes with.

https://github.com/CEED/libCEED/pull/145

**Comment by dmed256** [comment]
Oops, misread the hash. Thought it was the HEAD commit at the time.
I'll check this tonight, my bad

**Comment by jeremylt** [comment]
No worries, thanks for looking into it

**Comment by dmed256** [comment]
@jeremylt seems the new `kernelHash` method is messing something up

https://github.com/libocca/occa/blob/master/src/device.cpp#L442

Changing it back to `occa::hash(allProps)` seems to make libCEED tests pass again. I'll keep looking to find out the root cause, just wanted to update you on that

**Comment by v-dobrev** [comment]
By the way, @dmed256, I think this issue also affects mfem's engines-dev branch and probably occa-dev as well.

**Comment by dmed256** [comment]
@jeremylt @v-dobrev Just tested libCEED with origin/master (1450f7420484e984adc57ab5df070bd03c0ccbb8) and it passes again

**Comment by v-dobrev** [comment]
Thanks, David! I'll give it a try with mfem.

**Comment by v-dobrev** [comment]
The latest commit (https://github.com/libocca/occa/commit/780a06ae273ea037bf21452600ffdb17b93a312c) works OK with mfem (engines-dev).
