### ISSUE TITLE
unexpected single precision flop counts with nvprof

### ISSUE THREAD

**Issue by jlchan** [libocca/occa#201]
I'm seeing unexpected single precision operations popping up with nvprof.  These seem linked to special functions like "log" - when I run them, they seem to default to the single precision version.  Is there any way to look at the cached code to make sure the double precision versions of these functions are being run?

**Comment by jlchan** [comment]
Looks like this may just by my mistake not compiling with "nvcc -arch sm_30" for compute capability 3.0.

**Comment by jlchan** [comment]
Turns out this is a CUDA issue https://stackoverflow.com/questions/52119782/cuda-logarithm-nvprof-detects-single-precision-operations-in-double-precision.

Closing

**Comment by dmed256** [comment]
Ah, thanks!
