### ISSUE TITLE
Figure out how to properly dlopen/dlclose OpenMP kernels

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#208]
Currently we need OCCA to be compiled with OpenMP to build OpenMP kernels
The only reason is described here:
```cpp
namespace occa {
  namespace openmp {
    device::device(const occa::properties &properties_) :
      serial::device(properties_) {
      // Generate an OpenMP library dependency (so it doesn't crash when dlclose())
      omp_get_num_threads();
    }
    ...
```

Theoretically we should be able to compile OCCA without OpenMP and build OpenMP kernels based on the compiler used to build that kernel

Examples of this showing up elsewhere:
  - https://github.com/JuliaLang/julia/issues/10938
  - [stackoverflow/5200418](https://stackoverflow.com/questions/5200418/destroying-threads-in-openmp-c)
  - [stackoverflow/29117441](https://stackoverflow.com/questions/29117441/tricky-error-using-openmp-in-function-loaded-from-dynamic-libraries)

**Comment by pdhahn** [comment]
According to the links, this may need resolution by a fix on the OpenMP side.

However, as a workaround, would it be possible to execute the OCCA code containing the dlopen()/dlclose() within a child process (i.e., just forked into a memory sharing state, i.e., with no exec())? Then set up signal handlers in the parent and child in a suitable way so the child process can die bad (i.e., resulting from a SIGSEGV at the dlclose()) without killing the parent process.

**Comment by dmed256** [comment]
Closing since it's not really an issue as long as we know the workaround :sweat_smile:
