### ISSUE TITLE
Disable OpenCL at runtime if needed

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#209]
Sometimes the graphics driver is not setup properly for OpenCL, even if OpenCL is installed
```
  > occa info
  terminate called after throwing an instance of 'occa::exception'
    what():
  ---[ Error ]--------------------------------------------------------------------
      File     : <OCCA_DIR>/src/mode/opencl/utils.cpp
      Line     : 81
      Function : getPlatformCount
      Message  : OpenCL: Get Platform ID Count
      Error   : OpenCL Error [ -1001 ]: UNKNOWN ERROR
```
Test if `OpenCL` is enabled and fallback to `Serial` mode if needed, similar to how `OpenMP` mode does

**Comment by pdhahn** [comment]
As a related issue perhaps, I have to use program logic to detect whether OpenCL is configured for CPU and/or GPU before selecting the "available" OCCA mode. OpenCL is designed for this kind of configurability based on the installed OpenCL drivers. On one of my systems, as a slightly interesting example, I actually do not have an installed _CPU_ driver for OpenCL, although I do have one for the _GPU_. I could install the freeware AMD OpenCL driver for CPU, but I don't like the licensing terms.

I guess my point is, should the OCCA API also be extended to help out with my case? Like, "choose the _best available_ OpenCL mode, or fall back to Serial if none available"?

**Comment by pdhahn** [comment]
FYI my program logic is actually designed to detect the compute resources and choose a "best available" OCCA mode in the general case, according to a hierarchy of "compute power" (_viz._ performance).

Again, it would be a nice enhancement to the OCCA API if this were a feature available to everyone. If it were, then the issue here as you have defined it would be subsumed under that new feature, I think.

**Comment by dmed256** [comment]
Fixed in ab5cad0ee49f2bbff4a52efa3216bc0b9f141acd, along with CUDA and HIP modes

@pdhahn Might be good to expose some utilities for that, right now there are only _unofficial_ methods:

```cpp
int deviceType = occa::opencl::deviceType(platform_id, device_id);

if (deviceType & occa::opencl::info::CPU) {
    ...
} 
else if (deviceType & occa::opencl::info::GPU) {
    ...
}
```

**Comment by dmed256** [comment]
The issue was more of a problem with not being able to use OpenCL at runtime than checking if a device is good or not. I would prefer that logic is outside of OCCA, but maybe supporting those _unofficial_ methods might be useful for others

**Comment by pdhahn** [comment]
So I assume your changes here will not fall back to Serial if OpenCL is working for CPU, even if not for the GPU (opposite of my example but more consistent with the original issue description)?

**Comment by pdhahn** [comment]
In other words, say I specify OpenCL for GPU but that is not working. Then OCCA should first try to fall back to OpenCL with CPU. Then if that is not available, fall back to Serial.

**Comment by dmed256** [comment]
Yep, this was a fallback if OpenCL can't be loaded properly as opposed to "My choice of device isn't available"
