### ISSUE TITLE
Question: occa::properties FP32 define promoted to FP64 in kernel gen ?

### ISSUE THREAD

**Issue by tcew** [libocca/occa#215]
I am using 

```cpp
kernelInfo["defines/" "p_half"]= p_half;
kernelInfo["defines/" "p_third"]= p_third;
```

where p_third is a float variable for 1.f/3

When used in a kernel this code is generated:

```cpp
 const float S11 = 5.0000000000000000e-01 * (dudx + dudx) - 3.3333334326744080e-01 * divV;
```

Note that it has promoted these compiler constants to double precision. 

Question: is this expected behavior ?

**Comment by dmed256** [comment]
Weird, that is not intended behavior

The stringify call should be through:
https://github.com/libocca/occa/blob/master/src/tools/string.cpp#L129

I'll try to replicate it tonight and see where it's going wrong

**Comment by dmed256** [comment]
Tested it out today and floats seem to be printed properly
__main.cpp__
```cpp

  // Compile the kernel at run-time
  float p_half = (float) (1.0 / 2.0);
  float p_third = (float) (1.0 / 3.0);
  occa::properties kernelInfo;
  kernelInfo["defines/" "p_half"]= p_half;
  kernelInfo["defines/" "p_third"]= p_third;

  addVectors = device.buildKernel("addVectors.okl",
                                  "addVectors",
                                  kernelInfo);
```
__addVectors.okl__
```cpp
    ab[i] = a[i] + b[i] + p_half + p_third;
```
&rarr;
```cpp
        ab[i] = a[i] + b[i] + 5.00000000e-01f + 3.33333343e-01f;
```

**Comment by dmed256** [comment]
@tcew any difference between the 2 code snippets that could have caused that issue?

**Comment by tcew** [comment]
I am not sure what is causing this issue. Could it be related to the constants being used in arithmetic expressions ?

const dfloat S11 = p_half*(dudx+dudx) - p_third*divV;
        const dfloat S22 = p_half*(dvdy+dvdy) - p_third*divV;
        const dfloat S33 = p_half*(dwdz+dwdz) - p_third*divV;

**Comment by nnnunnn** [comment]
To help compiler select fp32 vs. fp64, how about loading params as local
vars before use, e..g.,

const dfloat third = (dfloat) p_third;
const dfloat half = (dfloat) p_half ;

const dfloat S11 = half * (dudx+dudx) - third * divV;
const dfloat S22 = half * (dvdy+dvdy) - third * divV;
const dfloat S33 = half * (dwdz+dwdz) - third * divV;

Nigel

**Comment by dmed256** [comment]
The result printed should come from the type the property value was set as
```cpp
kernelInfo["defines/" "p_half"] = 0;          // (int)    -> "0"
kernelInfo["defines/" "p_half"] = (float) 0;  // (float)  -> "0.0000000000f"
kernelInfo["defines/" "p_half"] = (double) 0; // (double) -> "0.0000000000000000000"
```
If it was directly in the kernel as `0.0001f` but the output came out as `0.0001`, that might be a bug
