### ISSUE TITLE
Suggestion: add a Donate link on project web page

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#218]
You should consider putting some sort of link on the libOCCA web page that allows appreciative users like me to make a modest voluntary $ donation to support the project.  I notice that some open source software projects do that (e.g., LibreOffice and many others).

**Comment by dmed256** [comment]
Thanks @pdhahn! 
Luckily I'm not doing too bad at the moment so I would prefer to not have a donation link, but I appreciate the offer :)
