### ISSUE TITLE
Use default runtime CUDA context and stream if it's set

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#224]
Try to get the current CUDA context to use
```
cuCtxGetCurrent
```
rather than create a new one
https://github.com/libocca/occa/blob/master/src/modes/cuda/device.cpp#L37
```c++
OCCA_CUDA_ERROR("Device: Creating Context",
                cuCtxCreate(&cuContext, CU_CTX_SCHED_AUTO, cuDevice));
```
to make it easier to interop with other apps

Make sure to set the stream if not creating the context

**Comment by v-dobrev** [comment]
Here is a short description of how the CUDA runtime API handles contexts: https://docs.nvidia.com/cuda/cuda-runtime-api/driver-vs-runtime-api.html#driver-vs-runtime-api (section "Context management").
