### ISSUE TITLE
atomic operations

### ISSUE THREAD

**Issue by tcew** [libocca/occa#228]
I am not sure what the current status of atomicAdd is for OpenCL. 

I can use atomicAdd in CUDA. 

There are earlier issues posted that allude to @atomic. 

Did this get implemented ? and if so what is the syntax for an FP64 floating point atomic add operation ?

**Comment by dmed256** [comment]
It hasn't been implemented yet. Closing since issue #118 has more info regarding its format.

The format will most likely look like:

### Atomic expressions

#### Inlined atomic
```cpp
@atomic arr[i] += value;
```

```cpp
arr[i] += value @atomic;
```

#### Single update-statement block
```cpp
@atomic {
    arr[i] += value;
}
```

### Block statements
```cpp
@atomic {
    arr1[i] += value;
    arr2[i] -= value;
}
```
