### ISSUE TITLE
Request: Create Contributor / Maintainer / Developer doco to assist and cultivate new contributors and maintainers

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#231]
As the number of feature requests for OCCA grows, I suggest addition of documentation targeted for new, aspiring contributors and maintainers.

1. Firstly, a Contributors Guide. Something that would help the aspiring OCCA developer (contributor, maintainer) learn more about the internals of OCCA workings and corresponding source code, in order to get past the learning curve threshold needed to actual attack these feature requests. Not just how to create back-ends.

Note just mechanical descriptions of classes and functions etc. like what is typically generated by doxygen against source code is useful in a limited way, but is not really sufficient in a practical sense.

2. Try to add more in-depth, informative Contributor Notes to various Request Issues as an assist. Like where to start and how-to insights. Do not assume the potential Contributor already knows as much about OCCA internals as the OCCA author(s) (which is what many of the notes that do exist seem to be like; i.e., notes-to-self).

I believe if such doco were available, it would help to get more people involved.

**Comment by pdhahn** [comment]
Note how-to-extend / modify the custom OCCA parser w.r.t. OKL language features is certainly not the only topic of interest here, even if it might be a good place to start. Nevertheless, something more comprehensive and top-down for OCCA internals is the real goal I think, if the idea is to attract Contributors / Maintainers. The parser internals would just be one component of such doco.

**Comment by dmed256** [comment]
Hi @pdhahn !

It's a good idea to update not only the API docs, but also add developer docs for adding to OCCA. I'm currently a focusing on adding a few more core features to OCCA but can prioritize documentation afterwards.

**Comment by pdhahn** [comment]
Repeating the guidelines on How to Contribute was a good point. But may I just further expound a bit on the nuance of what I meant by "contributor". It is not always someone who originates the feature idea / request who might also want to implement it and submit for acceptance. Rather, it can be a developer who is both willing and able (by virtue of being equipped with suitable knowledge about the internal workings of OCCA) to assist the OCCA author(s) with implementation of feature requests originated by others or the author(s) themselves (but still always to be submitted for acceptance).

Similarly for the "maintainer" who is someone who wants to assist by working to fix bugs that may have been detected / recorded by others including the OCCA author(s).

Such folks presumably would be especially on the alert to assist with issues marked "Help Wanted!". Their motivations to invest time and effort presumably would include solidification / stabilization of OCCA in order to bring it into full and useful maturity and thereby help grow its user base.

**Comment by kris-rowe** [comment]
This and other topics related to OCCA's open-source community standards will be split into several issues and addressed in the next release.
