### ISSUE TITLE
Add dependencies to the kernel hash

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#236]
Our current hashing strategy for kernels includes hashing:
- Device properties (e.g. mode and compiler flags)
- Kernel properties (e.g. defines and includes)
- Kernel source file

Only the kernel source is included in the hash. Because it's common to include files inside an `okl` file, kernels are sometimes incorrectly hashed. We need to include the dependencies in the `build.json` file in addition to the original source file.

**Comment by pdhahn** [comment]
also per issue #59 although that is now closed

**Comment by dmed256** [comment]
@pdhahn The initial implementation was to use the preprocessor and hash its source which is much more computationally intensive than checking dependencies and hashes.

The current implementation is still not perfect but should at least help with better kernel hashing

**Comment by dmed256** [comment]
Added in #237
