### ISSUE TITLE
wrapMemory() funtion in CUDA.cpp

### ISSUE THREAD

**Issue by iamagoofymonkey** [libocca/occa#25]
The wrapMemory() funtion in CUDA.cpp causes a runtime error.  The error occurs when finish() is called, but when I modified the code (see line 1300 in CUDA.cpp), I was able to get the kernel to execute successfully.  Below is my suggested patch/replacement for the wrapMemory() function.

   template <>
  memory_v* device_t<CUDA>::wrapMemory(void *handle_,
                                       const uintptr_t bytes){
    memory_v *mem = new memory_t<CUDA>;

    mem->dHandle = this;
    mem->size    = bytes;
    mem->handle  = (CUdeviceptr*) handle_;

    mem->memInfo |= memFlag::isAWrapper;

    return mem; 
  }

**Comment by dmed256** [comment]
Thanks for the patch, I'll add it tonight =)

**Comment by dmed256** [comment]
Just merged with master branch
