### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by bitflipper42** [libocca/occa#257]
Hello!

Really interested in the philosophy behind Occa and OKL, it sounds like it should fit our needs.

We are looking for the proper abstraction engine that would allow us to do image processing in Windows and Mac using any of OpenCL, Metal, D3D12 and/or direct CPU.  

While we are OK having separate kernel implementations per bottom API, OKL sounds very very interesting for us.  It would be a dream come true if we could have a single implementation of both the high level framework and the kernels as well.

Here are the questions:

1. Is there a chance/interest in supporting this project in Windows?
2. What is the status of the Metal project?
3. Is it possible to write the kernels directly in say, OpenCL or Metal for example?

We can probably put some work on getting it working in Windows/D3D12 if the project is interested in adding Windows to the supported platforms.

**Comment by dmed256** [comment]
Hi!

> 1. Is there a chance/interest in supporting this project in Windows?

There is someone in our research group who only runs OCCA on Windows and has sent us patches to keep it working. It might not be completely working in the current `master` branch, but can be fixed if there is someone knowledgeable about Windows development.

> 2. What is the status of the Metal project?

I'm able to run Metal kernels on my Macbook air (Mojave) but seems to be broken for older versions of Metal. 

> 3. Is it possible to write the kernels directly in say, OpenCL or Metal for example?

Yep, there are some examples found here:

 - C++: https://github.com/libocca/occa/tree/master/examples/cpp/interop_examples/native
 - OpenCL: https://github.com/libocca/occa/tree/master/examples/cpp/interop_examples/native
 - CUDA: https://github.com/libocca/occa/tree/master/examples/cpp/interop_examples/opencl

As long as there is a symbol to refer to in the native kernel, OCCA will pick it up.

> We can probably put some work on getting it working in Windows/D3D12 if the project is interested in adding Windows to the supported platforms.

That would be awesome! Definitely feel free to make more Github issues or email me if you need more info :)

David
