### ISSUE TITLE
Using streams with multiple devices

### ISSUE THREAD

**Issue by iamagoofymonkey** [libocca/occa#27]
I am unable to get my program to work with streams and multiple devices in mode=CUDA. So, as a test, I modified the addVectors example under examples/usingStreams/ to include and extra device.  The error is CUDA_ERROR_INVALID_HANDLE. See copy of modified code below.
```c++
#include <iostream>

#include "occa.hpp"

int main(int argc, char **argv){
  int entries = 8;

  float *a  = new float[entries];
  float *b  = new float[entries];
  float *ab = new float[entries];
 
  for(int i = 0; i < entries; ++i){
    a[i]  = i;
    b[i]  = 1 - i;
    ab[i] = 0;
  }   
 
  occa::device device;
  occa::device device1; // ADDED
  occa::kernel addVectors;
  occa::memory o_a, o_b, o_ab;
 
  occa::stream streamA, streamB;
 
  device.setup("mode = CUDA, deviceID = 0"); // UNCOMMENTED
  device1.setup("mode = CUDA, deviceID = 1"); //ADDED
  //device.setup("mode = OpenCL, platformID = 0, deviceID = 1"); //COMMENTED
 
  streamA = device.getStream();
  streamB = device.createStream();
 
  o_a  = device.malloc(entries*sizeof(float));
  o_b  = device.malloc(entries*sizeof(float));
  o_ab = device.malloc(entries*sizeof(float));
 
  addVectors = device.buildKernelFromSource("addVectors.okl",
                                            "addVectors");
 
  o_a.copyFrom(a);
  o_b.copyFrom(b);
 
  device.setStream(streamA);
  addVectors(entries, o_a, o_b, o_ab);
 
  device.setStream(streamB);
  addVectors(entries, o_a, o_b, o_ab);
 
  o_ab.copyTo(ab);
 
  for(int i = 0; i < entries; ++i)
    std::cout << i << ": " << ab[i] << '\n';
 
  delete [] a;
  delete [] b;
  delete [] ab;

  addVectors.free();
  o_a.free();
  o_b.free();
  o_ab.free();
  device.free();
  device1.free();  //ADDED
}
```

**Comment by dmed256** [comment]
Hi @iamagoofymonkey 

Weirdly enough I got an issue with that same error
I thought I fixed it in f0d541256235bcfbea0f025b6bc8c813ac074c2e by adding cuCtxSetCurrent in some operations like [when allocating memory](https://github.com/libocca/occa/blob/master/src/CUDA.cpp#L1343-L1344)
I'll check with your snippet tonight and see where I'm missing that call

Thanks again =)

**Comment by iamagoofymonkey** [comment]
Thanks man! We'll have to grab some sushi sometime soon, if you got the time?

**Comment by dmed256** [comment]
Added the fix in d658edb17342fdb6ada8392fa0c6f0d3a2e24c0b and it seems to work now. Mind testing it for me before I close the issue?
Thanks

**Comment by iamagoofymonkey** [comment]
Yup. I'm getting allergy shots all day, so I may not get all the testing done until Monday.

**Comment by dmed256** [comment]
np, any help is appareciated
