### ISSUE TITLE
Add filter hook to OKL source file reads when building kernels from source

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#281]
Please add the option to the OCCA API for the user to specify a filter hook applied at the time an OKL source file is read (i.e., in building a kernel from source). At least on Linux, this simply means calling `popen()` with the command sequence like `cat okl-source-file | filter filter-args`, whose output is read to obtain the source contents string to be parsed.

In my case, I would like to specify the venerable m4 preprocessor as the filter. This would allow me to define m4 macros for inlining pseudo-nested kernel function code within kernel bodies. Of course, I could (and do!) use `#define` but that requires EOL continuations for long multi-line texts. The m4 preprocessor is exceedingly more useful to my purposes and facilitates the illusion of OKL functions that implement parallel code blocks with `@outer` / `@inner`.

Of course, it would be extremely useful if the latter feature (once suggested I think by Dr. Warburton) were indeed implemented. But I presume that hasn't happened yet because of the effort involved. So the hook thing can help.

**Comment by dmed256** [comment]
This seems out of scope for building a kernel in OCCA. The user can handle performing the source code transformations in any way they want and use its output forbuilding the kernel from the output string.

**Comment by pdhahn** [comment]
You are right of course but I was just looking for something convenient.
