### ISSUE TITLE
b is not const?

### ISSUE THREAD

**Issue by amikstcyr** [libocca/occa#290]
https://github.com/libocca/occa/blob/e194bc58b46dd5e7317c6d2f14fd3b03bcaa0c2b/examples/cpp/06_unified_memory/main.cpp#L36

Not sure what is meant here... I see the kernel as not const for ab but b is const... ?

**Comment by dmed256** [comment]
Good catch, I must have forgotten to remove the `const` after updating all of the `addVectors.okl` files to use `@tile`!
