### ISSUE TITLE
runtime environment variables not used

### ISSUE THREAD

**Issue by amikstcyr** [libocca/occa#296]
Reproducer:

cd occa/examples/cpp/01_add_vectors
mkdir level1
cd level1
touch lev1.h

In addVectors.okl add:
#include "lev1,h"

make
./main
bombs it cannot find the file:

<SNIP>/.occa/cache/ce2653430e8d9a24/raw_source.cpp:3:2: Error: File does not exist
#include "lev1.h"

Now, one can play with the run time env variable (occa env)

export OCCA_INCLUDE_PATH=<put full path to add vector example>/level1
Still does not work.
Question: this variable supports OCCA_INCLUDE_PATH=<path1>:<path2>:...<pathN> ?

export OCCA_CXXFLAGS=-I<>/level1
Still does not work.

What works:

in addVectors.okl
put the full path to acces lev1.h
#include "<fullpath>/level1/lev1.h"

bash-4.2$ ./main
0: 1
1: 1
2: 1
3: 1
4: 1

**Comment by amikstcyr** [comment]
It seems that the OCCA_INCLUDE_PATH (runtime variable) is parsed and split on ":" - only - when an app is built. It has nothing to do with the runtime or any of the kernel files.

Now - this would be really practical that runtime is done at runtime. Hard coding paths in okl files is less than optimal especially for deployment or includes having includes inside them - all nested includes would need absolute paths...

**Comment by dmed256** [comment]
Fixed in #317
