### ISSUE TITLE
Query device memory

### ISSUE THREAD

**Issue by jkozdon** [libocca/occa#3]
As far as I can tell there is no mechanism in occa that allows me to query the main memory for a device.

Two ways that I could see doing this are
  1. an occa function that just returns the global memory size of the device (we currently only really care about this for opencl and cuda)
  2. an occa function that returns the device pointer, and let the user query the device themselves

Would either of these by feasible to implement within occa? We were having problems locking up our boxes when allocating to much memory on the device, so want to put in some checks to make sure this doesn't occur in our codes.

**Comment by dmed256** [comment]
Added device::maxBytesAvailable(), it will default to 0 if some error occurred when trying to access it (incase you want to add a check)

**Comment by dmed256** [comment]
Works on OSX, fixing it on Linux atm

**Comment by dmed256** [comment]
Seems to work on Linux, also added the memory information to [occa info]

**Comment by dmed256** [comment]
Last change, the function name:

  device:: maxBytesAvailable()-> device::memorySize()

seems easier for users to remember
