### ISSUE TITLE
okl: true bug

### ISSUE THREAD

**Issue by amikstcyr** [libocca/occa#305]
If the variable okl true is set (or false) then the other okl variables generate an error.
To reproduce:

use example 01 in c:

1- Use OpenMP mode (uncomment)
2- add:
  occaPropertiesSet(props, "okl", occaBool(1));
  occaPropertiesSet(props, "okl/include_paths", occaString("/usr/include"));

Second call will bomb because okl is a variable.

Solution would be to have okl/status = true or false (or okl/enabled).

**Comment by dmed256** [comment]
I think this was solved by changing `okl: false` ->  `okl/enabled: false`
