### ISSUE TITLE
occaParallelFor not automatically added in OpenMP mode

### ISSUE THREAD

**Issue by dshawul** [libocca/occa#31]
Is there a reason why that is ? I added it manually in my code but i was wondering if this is a bug or a feature in OCCA2 ?

**Comment by dmed256** [comment]
```C++
#pragma omp parallel for
occaOuterFor2 { occaOuterFor1 { occaOuterFor0 { ... } } }
```

would perform worse (or no better than) 

```C++
#pragma omp parallel for collapse(3)
occaOuterFor2 { occaOuterFor1 { occaOuterFor0 { ... } } }
```

For that reason, users can define

```C++
occaParallelFor2
occaOuterFor2 { occaOuterFor1 { occaOuterFor0 { ... } } }
```

```C++
occaParallelFor1
occaOuterFor1 { occaOuterFor0 { ... } } 
```

```C++
occaParallelFor0
occaOuterFor0 { ... } }
```

**Comment by dshawul** [comment]
Thanks David, that makes sense. 
I was concerned the default behavior of old kernels with OpenMP do not spawn threads.

**Comment by dmed256** [comment]
No problem, sorry about the confusion
