### ISSUE TITLE
Running on MIC

### ISSUE THREAD

**Issue by dshawul** [libocca/occa#32]
I am having trouble  to run on the Xeon Phi using the offload model. A simple program show below
prints 240 cores, but bin/occainfo does not detect the Xeon Phi (only CPU info is shown). I also tried to compile occa with OCCA_COI_ENABLED=1 but i learned this is deprecated, so I am trying to run in OpenMP mode. 

```
int main(){
     int nprocs;
    #pragma offload target(mic)
     nprocs = omp_get_num_procs();
     printf("Hello %d\n",nprocs);
     return 0;
}
```

With OpenMP mode I am redefining the outer loop of my kernels to run in parallel and on the MIC with:

```
 #define myOuterFor OCCA_PRAGMA("offload target(mic)") occaParallelFor occaOuterFor0
```

I got errors after I added the mic pragma:

```
 error: pointer variable "occaKernelArgs" in this offload region must be specified in an in/out/inout/nocopy clause
```

Is it possible to run OCCA in native mode ? I would like to launch more than one process per MIC card and a few threads instead of running threads only. But I guess this would be against the design of OCCA.

Daniel

**Comment by dmed256** [comment]
occaKernelArgs is a pointer with a few things, such as the dimension sizes
I guess you have to manually put that in the offload pragma

**Comment by dshawul** [comment]
Still having problem with using OCCA in offload mode on the older Knight's corner.
But it works well on the Knight's landing, which seems to be a regular processor,  in hybrid MPI+OpenMP mode using different combinations of processes & threads. So ignore my question about a problem running in native mode.
Daniel
