### ISSUE TITLE
[CMake] Incompatible flags passed to compiler

### ISSUE THREAD

**Issue by SFrijters** [libocca/occa#320]
The recent commit 7b2e817 introduced a compiler flag `-Wno-c++11-extensions` that is not accepted by at least the Intel compiler.

I have a PR coming soon that generalizes the checks for possible compiler flags and uses some more CMake standardization.

**Comment by JamesEggleton** [comment]
@SFrijters @dmed256 happy to report that this branch compiles fine on my macOS 10.14.6 system. FYI the bulk of newly-reported warnings are due to [-Wfloat-equal].

**Comment by dmed256** [comment]
@JamesEggleton Ah, good catch. I wasn't using that flag and just saw these:

```
/Users/dsm5/git/night/src/lang/primitive.cpp:439:69: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
    case primitiveType::float_  : return primitive(a.to<float>()    == b.to<float>());
                                                   ~~~~~~~~~~~~~    ^  ~~~~~~~~~~~~~
/Users/dsm5/git/night/src/lang/primitive.cpp:440:69: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
    case primitiveType::double_ : return primitive(a.to<double>()   == b.to<double>());
                                                   ~~~~~~~~~~~~~~   ^  ~~~~~~~~~~~~~~
/Users/dsm5/git/night/src/lang/primitive.cpp:465:69: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
    case primitiveType::float_  : return primitive(a.to<float>()    != b.to<float>());
                                                   ~~~~~~~~~~~~~    ^  ~~~~~~~~~~~~~
/Users/dsm5/git/night/src/lang/primitive.cpp:466:69: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
    case primitiveType::double_ : return primitive(a.to<double>()   != b.to<double>());
                                                   ~~~~~~~~~~~~~~   ^  ~~~~~~~~~~~~~~
```

In this case it should be fine to ignore the warnings since we're only trying to mimic the operators.

**Comment by SFrijters** [comment]
I will go through the warnings for the different compilers I use and try to provide fixes for them.

For the -Wfloat-equal warnings in particular I should be able to recycle something I used for a similar situation before.
