### ISSUE TITLE
testRmrf fails

### ISSUE THREAD

**Issue by SFrijters** [libocca/occa#326]
This is just a small thing, but for my CI (jenkins) user `testRmrf` fails.
I've looked into the implementation and my environment and it happens because the `jenkins` user is a local user and has a `$HOME` of `/foo/home/jenkins` instead of `/home/jenkins`, which I think is the tacit assumption in the `isSafeToRmrf` function.

In general, it feels to me like that function is giving a false sense of security, or could at least use some additional documentation, since from the function name I would never have guessed the criteria.

Also, in some sense it may also be too strict, because something like `/tmp/occa` should be 'safe' to remove even though it only has depth 2. Maybe it would be nicer to check if the normalized path is below the user's actual home directory instead, or something like that? That still wouldn't cover the `/tmp` case though.

**Comment by dmed256** [comment]
I've seen some horror cases where programs start deleting the root directory or user's home directory and wanted to avoid that even if it meant being too strict. Maybe we can whitelist some safe directories to delete, such as `/tmp`, that don't satisfy the current `isSafeToRmrf`?

**Comment by SFrijters** [comment]
Maybe we can check if any of the path components is equal to `occa`? It would make sense that occa-related paths would have occa in the name somewhere, and those should be 'safe' to delete? Unless someone's username is `occa`...

**Comment by dmed256** [comment]
I like that idea! It's simple to implement and seems safe enough
