### ISSUE TITLE
Compiler warnings with new CMake builds

### ISSUE THREAD

**Issue by SFrijters** [libocca/occa#327]
With the recently added warning flags in the CMake build, various compilers are complaining about things.

I'm working on a PR to fix these issues.

**Comment by noelchalmers** [comment]
I was also looking at this. My plan was to keep the warning flags for debug builds and suppress existing warnings on release builds. There's also a bunch of changes I had to make to hook the new cmake build system into an existing cmake project and other QoL changes. I can wait on your changes first though @SFrijters

**Comment by SFrijters** [comment]
My PR should be coming early next week; I have a local branch that treats the warnings for Intel and clang builds, but gcc was still complaining about some things and I will look into that on Monday.
