### ISSUE TITLE
[C] Inconsistent/unclear usage of OCCA_LFUNC

### ISSUE THREAD

**Issue by awehrfritz** [libocca/occa#333]
In the C-API, all function declarations in the header files have `OCCA_LFUNC` and `OCCA_RFUNC` around the return type like this:
https://github.com/libocca/occa/blob/560d8eb320dccb664427b44e58f7acff7bc5b35a/include/occa/c/base.h#L16

However, in the respective .cpp files, only `OCCA_RFUNC` is used consistently and `OCCA_LFUNC` is missing in various places. Here an example:
https://github.com/libocca/occa/blob/560d8eb320dccb664427b44e58f7acff7bc5b35a/src/c/base.cpp#L19

It's unclear to me why some functions have it and some don't; there doesn't seem to be a clear pattern.

You can find all instances in the source code like this:
``` sh
grep OCCA_RFUNC -r include/ src/ | grep ':[a-z].* OCCA_RFUNC'
```

Could someone please clarify whether this is intentional or an oversight?

**Comment by dmed256** [comment]
These macros are only used for Windows, where I thought we needed to add
```
__declspec(dllexport)
```
on the function signatures only in the headers

I could be wrong, specially since I don't work on WIndows. I'm ok with updating these macros/removing them if there's a better solution.

**Comment by awehrfritz** [comment]
Ok, thanks for the clarification. I have no idea about how this should be done on Windows either (I have never coded on Windows, nor do I use Windows for pretty much anything else either).

So, if this is only supposed to be used in the header, then we could in principle just remove `OCCA_LFUNC` from the .cpp files entirely, right?

**Comment by dmed256** [comment]
Removed in #434
