### ISSUE TITLE
Aligned malloc in occa ?

### ISSUE THREAD

**Issue by dshawul** [libocca/occa#35]
Hi David,
I would like to use vector intrinsics when running on the CPU in OpenMP mode. For this purpose, I need to change all occaDeviceMallocs with the corresponding __aligned_malloc, f.i to ensure 32 byte alignement for vdouble4. I could not find an occaDeviceAignedMalloc in OCCA unfortunately.

The vector.hpp file has some vector intrinsics towards the bottom of the file, which is not complete yet, so I wrote a new class which is not working properly right now. I am guessing the reason may be byte alignment issues.

Daniel

**Comment by dmed256** [comment]
Hi Daniel
Right now, most memory allocations use [occa::cpu::malloc](https://github.com/libocca/occa/blob/master/src/Serial.cpp#L524) which can be setup as an [environment variable](https://github.com/libocca/occa/blob/d658edb17342fdb6ada8392fa0c6f0d3a2e24c0b/src/tools.cpp#L67-L79)
The default alignment is 32 bytes

**Comment by dshawul** [comment]
Thanks David. I will use the environment variable to change the default alignment to 64 bytes for AVX-512. One more thing, the double4 and others in vector.hpp seem to be much slower than should be, due to the default constructors  initializing the components to 0. If I just declare the constructor as: double4() {}, I get a time to solution difference of 100 sec versus 160 sec in my code, which I think big.
Daniel

**Comment by dshawul** [comment]
Another cause of the difference could be a lack of explicit copy constructor in double4 class. Here is mydouble4 class without intrinsics.

```
struct mydouble4 {

  union {
    __m256d reg;
    struct { double x,y,z,w; };
  };
  
  mydouble4() {
  }
  mydouble4(const mydouble4& a) : 
    x(a.x), y(a.y), z(a.z), w(a.w) {
  }
  mydouble4(const double& a) :
    x(a), y(a), z(a), w(a) {
  }
  mydouble4(const double& a, const double& b, const double& c, const double& d) :
    x(a), y(b), z(c), w(d) {
  }
};
inline mydouble4  operator - (const mydouble4 & a) {
    return mydouble4(-a.x,-a.y,-a.z,-a.w);
}
inline mydouble4 & operator += (mydouble4 & a, const mydouble4 & b) {
    a.x += b.x; a.y += b.y; a.z += b.z; a.w += b.w;
    return a;
}
inline mydouble4 & operator -= (mydouble4 & a, const mydouble4 & b) {
    a.x -= b.x; a.y -= b.y; a.z -= b.z; a.w -= b.w;
    return a;
}
inline mydouble4 & operator *= (mydouble4 & a, const mydouble4 & b) {
    a.x *= b.x; a.y *= b.y; a.z *= b.z; a.w *= b.w;
    return a;
}
inline mydouble4 & operator /= (mydouble4 & a, const mydouble4 & b) {
    a.x /= b.x; a.y /= b.y; a.z /= b.z; a.w /= b.w;
    return a;
}
inline mydouble4 operator + (const mydouble4 & a, const mydouble4 & b) {
    return mydouble4( a.x + b.x, a.y + b.y, a.z + b.z, a.w + b.w);
}
inline mydouble4 operator - (const mydouble4 & a, const mydouble4 & b) {
    return mydouble4( a.x - b.x, a.y - b.y, a.z - b.z, a.w - b.w);
}
inline mydouble4 operator * (const mydouble4 & a, const mydouble4 & b) {
    return mydouble4( a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w);
}
inline mydouble4 operator * (const mydouble4 & a, const double & b) {
    return mydouble4( a.x * b, a.y * b, a.z * b, a.w * b);
}
inline mydouble4 operator * (const double & b, const mydouble4 & a) {
    return mydouble4( a.x * b, a.y * b, a.z * b, a.w * b);
}
inline mydouble4 operator / (const mydouble4 & a, const mydouble4 & b) {
    return mydouble4( a.x / b.x, a.y / b.y, a.z / b.z, a.w / b.w);
}
inline mydouble4  abs4(const mydouble4 & a) {
    return mydouble4( occaFabs(a.x), occaFabs(a.y), occaFabs(a.z), occaFabs(a.w)); 
}
```

**Comment by dmed256** [comment]
I'll have to change the include/occa/defines/vector.hpp to include the register if it's being compiled with it later
