### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#350]
Just did a git pull to update. The latest commit per git log is

`commit ddccbd590b9c7762e70ce07d26380663de751b92
Author: David Medina <dmed256@gmail.com>
Date:   Sun May 31 00:29:21 2020 -0400`

My make (platform: g++ v. 5.1 on CentOS 6 with Intel Xeon 5160's) now fails thus:

`[  1%] Building CXX object src/CMakeFiles/libocca.dir/lang/printer.cpp.o
.../src/lang/printer.cpp: In member function \u2018int occa::lang::printer::indentationSize()\u2019:
/vol1/athabasca/apps/occa/occa_1-clone/src/lang/printer.cpp:60:26: error: value computed is not used [-Werror=unused-value]
       (int) indent.size();
                          ^
.../src/lang/printer.cpp:61:5: error: no return statement in function returning non-void [-Werror=return-type]
     }
     ^
cc1plus: all warnings being treated as errors`

It looks like this is simply missing a `return`?

**Comment by dmed256** [comment]
Whoops my bad, not sure how that wasn't caught in the tests. Fixed in 5b33570b5f3db0d38005a7b6fb8634ed4fb4b72d

Thanks for the heads up!
