### ISSUE TITLE
build issue after latest update

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#360]
I just did another github update. I am using the `cmake`-generated `Makefile`. Now I have the following error during compilation:

`[  0%] Building CXX object src/CMakeFiles/libocca.dir/lang/tokenContext.cpp.o
.../occa/occa_1-clone/src/lang/tokenContext.cpp: In member function \u2018void occa::lang::tokenContext_t::getSkippedTokens(occa::lang::tokenVector&, int, int)\u2019:
.../occa/occa_1-clone/src/lang/tokenContext.cpp:243:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       if (start >= tokenIndices.size()) {

cc1plus: all warnings being treated as errors`

This signed/unsigned issue is normally just a warning case of course.

**Comment by dmed256** [comment]
Hi @pdhahn ! 

Looks like I forgot a `(int)` cast. I'll add the warnings as errors if the flag is not already there this weekend.

Thanks for the heads-up,
David

**Comment by dmed256** [comment]
Fixed in #361
