### ISSUE TITLE
buildKernel properties:  "okl/include_paths" when "okl" is false?

### ISSUE THREAD

**Issue by RonRahaman** [libocca/occa#377]
I've got a question about the `kernelProps` argument to `serial::device::buildKernel`.  

I'm building a serial kernel, and I'm passing `kernelProps` such that the `"okl"` node is set to `false`.  However, that seems to cause problems when `serial::device::buildKernel` eventually [calls `parser.parseFile()`](https://github.com/libocca/occa/blob/7b9b2a97879c1f2a384c4fed234aece4d331e00d/src/modes/serial/device.cpp#L187).  Looks like, eventually, a `preprocessor_t` is constructed, and [it expects an `"okl/input_paths"` node in the properties](https://github.com/libocca/occa/blob/7b9b2a97879c1f2a384c4fed234aece4d331e00d/src/lang/preprocessor.cpp#L36).  However, since I've set the `"okl"` node to `false`, the `"okl/"` node doesn't exist, and I get an error message saying that.  

Am I definining `kernelProps` incorrectly for a serial kernel?

**Comment by dmed256** [comment]
We ran into that issue so we changed it to
```
["okl/enabled"] = false
```

**Comment by RonRahaman** [comment]
Perfect, thanks!
