### ISSUE TITLE
Events in a non NULL stream are not recognized

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#378]
Looks like it is (implicitly) assumed that events take place in the NULL stream:
https://github.com/libocca/occa/blob/master/src/modes/cuda/device.cpp#L146

Is there any reason not to use the current stream?

**Comment by noelchalmers** [comment]
Can just copy what HIP does here @dmed256 

https://github.com/libocca/occa/blob/2a74ff717424ccdef0779e764aa576128e375b8d/src/modes/hip/device.cpp#L135
