### ISSUE TITLE
Add support for non-blocking streams

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#379]
Currently all streams are synced w.r.t. the NULL stream:
https://github.com/libocca/occa/blob/master/src/modes/cuda/device.cpp#L132

**Comment by noelchalmers** [comment]
After #378 is patched, the only thing that could be in the NULL stream is blocking mem copies. Is a option non-implicitly-synchronizing NULL stream really required when the application developer can simply use async copies in other streams? What's the benefit here?

**Comment by stgeke** [comment]
It would allow a user to overlap kernels in a non NULL stream with kernels in the NULL stream.

**Comment by noelchalmers** [comment]
I'm aware, but my question is why should this be a separate option in OCCA's stream creation. The same behavior can be obtained by the application developer putting all work in non-NULL streams as usual. OCCA itself puts nothing in the NULL stream, aside from blocking memcpys, which can be avoided by the developer by using async copies.

**Comment by stgeke** [comment]
It's just for convenience or if you're a lib developer which cannot control what happens in the upstream application. Just mimicking what e.g. the CUDA API exposes with cudaStreamNonBlocking.
