### ISSUE TITLE
Re-use events in tagStream

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#380]
Currently an event is created for every call:
https://github.com/libocca/occa/blob/master/src/modes/cuda/device.cpp#L142

This might add an overhead which can be avoided.

**Comment by noelchalmers** [comment]
I drafted a PR to do this some time back #280. However, my tests didn't reveal any noticeable overhead in event creation. Do you have a test that shows the event creation has overhead?

**Comment by dmed256** [comment]
Closing for now unless we find out there is actually a performance hit.
