### ISSUE TITLE
Adding `scripts/`, `src/`, etc. to installation?

### ISSUE THREAD

**Issue by RonRahaman** [libocca/occa#381]
Would you consider adding `scripts/` and `src/` to the OCCA installation, which is created by `make install`?  I think it would be great if, after installation, it didn't matter what happened to the source and build directories.  In that case, the installation directory could be the `OCCA_DIR`.  

It could really help our larger projects that are using OCCA apps.

**Comment by dmed256** [comment]
As part of #124, we stripped most of the private parts out of include and scripts :disappointed:
