### ISSUE TITLE
CUDA programming guide violation

### ISSUE THREAD

**Issue by AntoineFroger** [libocca/occa#382]
You are currently calling `cuInit` in the constructor of the library as a result of the definition of the `mode` global variable in the `registration.cpp` source file:  https://github.com/libocca/occa/blob/master/src/modes/cuda/registration.cpp#L42

If an application links with the `occa` library, `cuInit` will be called before `main`.  This is undefined behavior per the CUDA programming guide:  https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#initialization

> Note: The CUDA interfaces use global state that is initialized during host program initiation and destroyed during host
program termination. The CUDA runtime and driver cannot detect if this state is invalid, so using any of these interfaces
(implicitly or explicity) during program initiation or termination after main) will result in undefined behavior.

[Nsight Systems](https://developer.nvidia.com/nsight-systems) is unable to trace CUDA if the driver is initialized before `main` is called.  A direct consequence of the `occa` library calling `cuInit` in a static constructor is that it makes Nsight Systems' unable to trace CUDA for applications that directly link against the library.

**Comment by dmed256** [comment]
Oh interesting, thanks for flagging this!
We can move this as a lazy call when fetching for device modes or creating the first CUDA device.

**Comment by dmed256** [comment]
Oh wow, Github is smart now and auto-closes linked issues :thinking: 
Let me know if there is still an issue, but I think the lazy initialization should fix things now :)

**Comment by AntoineFroger** [comment]
Sorry for the late reply.  It effectively seems to have fixed the issue.  Thanks!
