### ISSUE TITLE
math functions

### ISSUE THREAD

**Issue by jkozdon** [libocca/occa#4]
A number of the math functions are wrapped in occa already, for instance occasqrt.

Would it be possible to wrap the rest of the opencl supported math functions? 
   https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/mathFunctions.html

I particularly need hypot, but figure it could be worth just wrapping them all (or at least the opencl/cuda intersection).

**Comment by dmed256** [comment]
Most functions in both CUDA and OpenCL are included by now, so I'm closing this
