### ISSUE TITLE
Large number of warnings when compiling with GCC 8.3.0

### ISSUE THREAD

**Issue by SFrijters** [libocca/occa#401]
GCC in release mode is showing an excessive number of warnings in the `modes` code, most of the type `-Wmaybe-uninitialized`. It doesn't look like any of the warnings are serious and while fixing some of the warnings is easy, for non-primitive variable types it will not make the code any prettier. Maybe the warning should be selectively repressed in the offending files?

Also, there is a single `-Wstrict-aliasing`:
```
/path/to/occa/src/modes/cuda/memory.cpp: In constructor ‘occa::cuda::memory::memory(occa::modeDevice_t*, occa::udim_t, const occa::properties&)’:
/path/to/occa/src/modes/cuda/memory.cpp:11:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         cuPtr((CUdeviceptr&) ptr),
```

**Comment by dmed256** [comment]
We've cleaned up quite a lot of errors since this ticket was created. If any more show up, please send over a PR to fix it since I can't reproduce locally :disappointed:.
