### ISSUE TITLE
Release v1.1.0 missing more recent commits

### ISSUE THREAD

**Issue by jeremylt** [libocca/occa#402]
It looks like v1.1.0 includes commits up to b6d21d58dd445cd6ca47c85938449ba079ecf273
but libCEED needs commits up to 56eb9eaefb461e9a66064b1e04f532f8614ac086

Was this intended? Will there be a release with these commits soon?

See also: https://travis-ci.com/github/CEED/libCEED/jobs/383262735

**Comment by dmed256** [comment]
Whoops, I'll recreate the tag. It was meant to be current HEAD in `main`

**Comment by dmed256** [comment]
Should be fixed now:
![image](https://user-images.githubusercontent.com/1812355/92814464-2c769d80-f391-11ea-8cc2-e80431548cef.png)

Thanks for flagging this issue!
