### ISSUE TITLE
[HIP] HIP_PLATFORM_HCC is needed for ROCM3.8

### ISSUE THREAD

**Issue by yslan** [libocca/occa#403]
On a machine that have access to both Nvidia GPU and AMD GPU, it will not choose the right environment by default.

I found that I have to put the flag `-D__HIP_PLATFORM_HCC__` into `OCCA_CXXFLAGS`, otherwise it will give errors.
`error ("Must define exactly one of _ _ HIP_PLATFORM_HCC _ _ or _ _ HIP_PLATFORM_NVCC _ _");`

rocm3.8 
gcc8.1

**Comment by noelchalmers** [comment]
OCCA's build system relies on finding the platform (HIP vs NVCC) from the hipconfig utility, located in /opt/rocm/bin/hipconfig by default. On a system with both a ROCm and CUDA installs, it's possible the platform needs to be set by the user to specify what behavior is desired. 

You should be able to set HIP_PLATFORM=hcc to instruct both the hipconfig utility and OCCA's build system to target AMD devices through HIP, or set HIP_PLATFORM=nvcc to target Nvidia devices. 

If that doesn't work, can you post the result of running `hipconfig --platform` on your system?

**Comment by yslan** [comment]
I did try `export HIP_PLATFORM=hcc`, but that's not sufficient. 

`hipconfig --platform` does show `hcc`

**Comment by noelchalmers** [comment]
Cool. And what about `hipconfig --cpp_config` ?

**Comment by yslan** [comment]
```
hipconfig --cpp_config
-D__HIP_PLATFORM_HCC__=  -I/opt/rocm-3.8.0/hip/include -I/opt/rocm-3.8.0/llvm/bin/../lib/clang/11.0.0 -I/opt/rocm-3.8.0/hsa/include -D__HIP_ROCclr__
```

**Comment by noelchalmers** [comment]
Looks like the `-D__HIP_PLATFORM_HCC__=` is being added properly from that. Are these flags and include paths present on your g++ compile lines when building OCCA?

**Comment by yslan** [comment]
I realize I didn't set HIP_PLATFORM properly...

So, if using `export HIP_PLATFORM=hcc`, then we don't need `-D__HIP_PLATFORM_HCC__` flag.
Thank!
