### ISSUE TITLE
In OpenCL mode kernel hash changes with platform&deviceID

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#422]
https://github.com/libocca/occa/blob/main/src/modes/opencl/device.cpp#L74
This way other devices cannot load a kernel from cache.

**Comment by dmed256** [comment]
We definitely need to cache by platform (e.g. CPU vs GPU) but not sure if we have to cache by device ID. Do you know if OpenCL guarantees multiple devices for the same platform use the same binaries? I would think this might be an issue with distinct NVIDIA/AMD GPUs :thinking:

**Comment by noelchalmers** [comment]
Some things to keep in mind:

- An OpenCL platform can have several different devices, potentially from different vendors (e.g. Apple's OpenCL).
- An OpenCL device can belong to several different platforms (e.g. a device can have OpenCL implementations from different vendors).

There are OpenCL extensions provided by NV and AMD that can determine more details on the device typologies, but AFAIK they are not available on Windows. Not sure about Intel extensions. 

One option to do what @stgeke is asking for is to make the assumption that devices in the same platform with the same name & vendor are "the same". I.e. make the hash depend on the names returned by CL_PLATFORM_NAME, CL_PLATFORM_VENDOR, CL_DEVICE_NAME, and maybe CL_DEVICE_VEDNDOR.

**Comment by dmed256** [comment]
>  I.e. make the hash depend on the names returned by CL_PLATFORM_NAME, CL_PLATFORM_VENDOR, CL_DEVICE_NAME, and maybe CL_DEVICE_VENDOR.

Now that you mention it, probably safer to hash by these values rather than just the IDs!

**Comment by stgeke** [comment]
This implies that we have to precompile kernel for all device IDs separately.

**Comment by noelchalmers** [comment]
> This implies that we have to precompile kernel for all device IDs separately.

Not unless the devices report to be physically different models. I'm suggesting to hash by the platform name and vendor plus the device name and vendor, _rather_ than the platformID and deviceID. If two devices report the same name and vendor, and are present in the same OpenCL platform, they should find the same cached files.
