### ISSUE TITLE
Default compiler flag dlcm=cg for CUDA backend

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#430]
What's the reason to enforce this compiler flag by default?

**Comment by dmed256** [comment]
I don't remember since it was a long time ago. I'm open to changing these flags if there's a better alternative.

**Comment by stgeke** [comment]
I think you can just remove it. It's more a performance tweak than anything else.

**Comment by dmed256** [comment]
If it's not hurting then I'll keep it as is. If there is a technical reason to keep it, replace it, or remove it, I'm more than happy to change it.

**Comment by stgeke** [comment]
It can have a negative performance impact that's why it should not be the default otherwise the user has no option to change it.

**Comment by kris-rowe** [comment]
This is duplicated in #565 and resolved by #569 .
