### ISSUE TITLE
compiler error after update from repository

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#443]
Just did a git pull and fresh build but got the following errors. Platform is CentOS 6 (latest/last) + dual Xeons + 32GB memory.

>`[ 98%] Building CXX object examples/cpp/11_native_cpp_kernels/CMakeFiles/examples_cpp_11_native_cpp_kernels.dir/main.cpp.o`
`.../occa/occa_1-clone/examples/cpp/11_native_cpp_kernels/main.cpp: In function int main(int, const char**):`
`.../occa/occa_1-clone/examples/cpp/11_native_cpp_kernels/main.cpp:41:4: `**error: converting false to pointer type for argument 2** `of occa::jsonKeyValue::jsonKeyValue(const string&, const char*) [-Werror=conversion-null]
   });`
`    ^
cc1plus: all warnings being treated as errors`
`make[2]: *** [examples/cpp/11_native_cpp_kernels/CMakeFiles/examples_cpp_11_native_cpp_kernels.dir/main.cpp.o] Error 1`
`make[2]: Target `examples/cpp/11_native_cpp_kernels/CMakeFiles/examples_cpp_11_native_cpp_kernels.dir/build' not remade because of errors.`
`make[1]: *** [examples/cpp/11_native_cpp_kernels/CMakeFiles/examples_cpp_11_native_cpp_kernels.dir/all] Error 2`

>`[ 98%] Built target cpp_example_12_addVectors_c`
`[ 98%] Building CXX object examples/cpp/12_native_c_kernels/CMakeFiles/examples_cpp_12_native_c_kernels.dir/main.cpp.o`
`.../occa/occa_1-clone/examples/cpp/12_native_c_kernels/main.cpp: In function int main(int, const char**):`
`.../occa/occa_1-clone/examples/cpp/12_native_c_kernels/main.cpp:44:4: `**error: converting false to pointer type for argument 2**` of occa::jsonKeyValue::jsonKeyValue(const string&, const char*) [-Werror=conversion-null]
   });`
`    ^
cc1plus: all warnings being treated as errors`
`make[2]: *** [examples/cpp/12_native_c_kernels/CMakeFiles/examples_cpp_12_native_c_kernels.dir/main.cpp.o] Error 1`
`make[2]: Target `examples/cpp/12_native_c_kernels/CMakeFiles/examples_cpp_12_native_c_kernels.dir/build' not remade because of errors.`

**Comment by dmed256** [comment]
Hey @pdhahn!

Long time no chat, hope you're doing well. Thanks for the heads up, I have a PR to hopefully address this issue.

**Comment by dmed256** [comment]
Looks like #444 auto-closed this ticket but feel free to re-open it if you're still seeing this casting issue :)
