### ISSUE TITLE
Keeping OCCA_VERSION_STR up-to-date

### ISSUE THREAD

**Issue by SFrijters** [libocca/occa#447]
The latest tag on the repository seems to be `v1.1.0`, but `OCCA_VERSION_STRING` (and its friend `OCCA_VERSION`) are still on 1.0.9.

Should this be kept in sync manually, or is it better to automate it somehow?

I am personally a fan of baking in a version taken from git somehow (e.g. some variant of `git describe`), but that still doesn't solve the problem of building the code from a tarball or something like that.

**Comment by dmed256** [comment]
Good catch. We should standardize a commit before tagging a release such includes changes like that. Not sure how to setup a test for it since it would be caught after the fact.

**Comment by dmed256** [comment]
I updated the version to `1.2.0` in #442 since I'm planning on versioning soon. I'll try to remember updating the versions before tagging in the future
