### ISSUE TITLE
Presumed race condition in caching

### ISSUE THREAD

**Issue by jedbrown** [libocca/occa#449]
In trying to address remaining concerns in https://github.com/CEED/libCEED/pull/688, I've been switching between occa main and 1.1.0 (the version that was working previously). I clean, remove `~/.occa`, and rebuild. Sometimes I get errors like below. Seems to be a race conditioning related to caching. We typically `make -j64 test`.

If this issue is hard to fix (or others may persist), how would you recommend isolating our build environments so that there is no chance of colliding with stale caches?

```
not ok 33 t521-operator /gpu/hip/occa stderr
# +terminate called after throwing an instance of 'occa::exception'
# +what():
# +---[ Error ]--------------------------------------------------------------------
# +File     : /home/gitlab-runner/builds/N8GCsqus/0/libceed/occa-1.1.0/src/tools/sys.cpp
# +Line     : 855
# +Function : dlopen
# +Message  : Error loading binary [5f0237e1aff76bcc/launcher_binary] with dlopen: /home/gitlab-runner/.occa/cache/5f0237e1aff76bcc/launcher_binary: file too short
# +Stack
# +19 occa::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char
> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# +18 occa::sys::dlopen(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, occa::io::lock_t const&)
# +17 occa::serial::device::buildKernelFromBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_t
raits<char>, std::allocator<char> > const&, occa::properties const&, occa::lang::kernelMetadata_t&)
# +16 occa::serial::device::buildKernelFromBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_t
raits<char>, std::allocator<char> > const&, occa::properties const&)
# +15 occa::serial::device::buildKernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char
>, std::allocator<char> > const&, occa::hash_t, occa::properties const&, bool)
# +14 occa::serial::device::buildLauncherKernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_tra
its<char>, std::allocator<char> > const&, occa::hash_t)
# +13 occa::launchedModeDevice_t::buildLauncherKernel(occa::hash_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string
<char, std::char_traits<char>, std::allocator<char> > const&, occa::lang::sourceMetadata_t)
# +12 occa::launchedModeDevice_t::buildKernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_trait
s<char>, std::allocator<char> > const&, occa::hash_t, bool, occa::properties const&)
# +11 occa::launchedModeDevice_t::buildKernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_trait
s<char>, std::allocator<char> > const&, occa::hash_t, occa::properties const&)
# +10 occa::device::buildKernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::
allocator<char> > const&, occa::properties const&) const
# +9 occa::device::buildKernelFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<cha
r>, std::allocator<char> > const&, occa::properties const&) const
# +8 ceed::occa::CpuOperator::buildApplyAddKernel()
# +7 ceed::occa::Operator::applyAdd(ceed::occa::Vector*, ceed::occa::Vector*, CeedRequest_private**)
# +6 ceed::occa::Operator::ceedApplyAdd(CeedOperator_private*, CeedVector_private*, CeedVector_private*, CeedRequest_private**)
# +5 /home/gitlab-runner/libceed/lib/libceed_test.so(CeedOperatorApplyAdd+0x42)
# +4 /home/gitlab-runner/libceed/lib/libceed_test.so(CeedOperatorApply+0x20d)
# +3 build/t521-operator(+0x1daa)
# +2 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea)
# +1 build/t521-operator(+0x11fa)
```

**Comment by dmed256** [comment]
Thanks for bringing it up. We're using file locks to handle race conditions, I wonder if there's a bug on that :thinking:

**Comment by dmed256** [comment]
I'll look into more multi-process locking solutions. Also, the HIP bug is on `main` now

**Comment by SFrijters** [comment]
FWIW, I have started seeing this problem intermittently now as well I think.

**Comment by dmed256** [comment]
I'll try a `flock` implementation sometime this week rather than using `mkdir` and see how it goes

**Comment by jedbrown** [comment]
If you can summarize the current strategy, I might be able to help suggest an atomic strategy that doesn't involve locking.

**Comment by dmed256** [comment]
The current steps are:
```
- Hash the kernel source + props
- Check if there is a binary for the kernel given the hash
  Yes -> 
      - Check if there is a success file already created (created after compiling to ensure writing to the file has finished)
        Yes ->
            - Build the kernel from the binary file
        No ->
            - Wait for the success file and then build the kernel from the binary file
  No -> 
      - Try to lock the file. Did I create the lock?
        Yes ->
            - Build the kernel source
            - Compile and create the binary file
            - Create the success file
            - Release the lock (delete the lock directory)
        No ->
            - Wait for the lock to be released
            - Build the kernel from the binary file
```

**Comment by jedbrown** [comment]
Seems racy when one process creates the success file, but hasn't completed writing it. Better to `mkstemp(3)` and write the file there, then `rename(3)` to the proper name. I assume that if multiple processes build concurrently, they create the same file. In that case, they don't need locks, just
```
try to open true_binary
if success, read it
else mkstemp and write the file, then rename to true_binary
```
The rename operation is atomic, and old file descriptors remain valid even if the rename replaces the version on the file system. If you do this, you don't need a lock or to poll for completion.

**Comment by dmed256** [comment]
The process that compiles the kernel makes the success file after it's done writing the binary. So I'm not sure where the race condition can occur there. However, I think the rename approach is cleaner and simpler than having the success file. 

We want the lock to prevent multiple kernel compilations occurring at the same time, but I guess it's pretty much the same amount of time taken to compile as it is to wait. This does clean up a lot of locking logic, might be worth trying out!

**Comment by dmcdougall** [comment]
> old file descriptors remain valid even if the rename replaces the version on the file system

Is that true for network-mounted file systems as well?

**Comment by jedbrown** [comment]
> Is that true for network-mounted file systems as well?

It's a POSIX semantic, so true for the likes of NFS, but not for DAOS and other object stores.

> If the link named by the new argument exists and the file's link count becomes 0 when it is removed and no process has the file open, the space occupied by the file shall be freed and the file shall no longer be accessible. If one or more processes have the file open when the last link is removed, the link shall be removed before rename() returns, but the removal of the file contents shall be postponed until all references to the file are closed.
https://pubs.opengroup.org/onlinepubs/9699919799/functions/rename.html

**Comment by SFrijters** [comment]
Update on this: I've implemented a fix of sorts using the temp file -> rename semantics mentioned earlier.
It seems to work in our tests (no more zero-length files, yay), but it still needs some fine-tuning I think. I will try to open a PR in a reasonable state soon and then it can be reviewed/iterated on. Also, I will need help with the Windows side of things as I don't have a setup to test that.

**Comment by dmed256** [comment]
Used @SFrijters 's solution in #505, thank you @SFrijters !
