### ISSUE TITLE
OpenCL header warnings

### ISSUE THREAD

**Issue by noelchalmers** [libocca/occa#451]
Compiling with OpenCL enabled (AMD and Nvidia platforms) spits a bunch of repeated warnings:
```
In file included from /usr/include/CL/cl.h:32,
                 from /home/nchalmer/occa/src/occa/internal/modes/opencl/polyfill.hpp:9,
                 from /home/nchalmer/occa/src/occa/internal/modes/opencl/utils.hpp:6,
                 from /home/nchalmer/occa/src/occa/internal/modes/opencl/utils.cpp:3:
/usr/include/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |                                                                                                        ^
```
I think it's easy enough to just add a `#define CL_TARGET_OPENCL_VERSION 220` before including the OpenCL headers. Does anyone know of potential side effects of doing so? Impact on Intel platforms?

**Comment by dmed256** [comment]
Looking at the [docs](https://github.com/KhronosGroup/OpenCL-Headers#compiling-for-a-specific-opencl-version), seems ok to set it to `220` as long as OCCA still builds

```cpp
#ifndef CL_TARGET_OPENCL_VERSION
#  define CL_TARGET_OPENCL_VERSION 220
#endif
```

**Comment by krowe-alcf** [comment]
I see the same warning using the latest Intel SDK. If this can just be set once--either in polyfill.hpp or compiledDefines.hpp--then it will be easy enough to change later if needed.

OpenCL 3.0 breaks backwards compatibility with OpenCL 2.0+ by making some features optional: when an API call is made an error code is returned. I don't think that OCCA is using any of these features so it unlikely to cause issues.

**Comment by dmed256** [comment]
Thank you @krowe-alcf!
