### ISSUE TITLE
Intel compiler does not like that line...

### ISSUE THREAD

**Issue by amikstcyr** [libocca/occa#471]
https://github.com/libocca/occa/blob/e4c7e4f442175ea1c472e7ad2f7266bfc310d361/include/occa/functional/array.hpp#L453

Intel compiler complains that size is not used in that method.
Fine... deleting the line in question obviously makes the compiler choke on:

https://github.com/libocca/occa/blob/e4c7e4f442175ea1c472e7ad2f7266bfc310d361/include/occa/functional/array.hpp#L456

Seems like a compiler issue ... (reports that size is undefined!!!)

```
occa::scope fnScope({
        {"size", (int) length()}, <----
        {"offset", offset},
        {"emptyValue", emptyValue},
      });
```
Seems to fix Intel nonsense.

**Comment by dmed256** [comment]
Woah weird... 

I'll go ahead and replace those lines later today, thanks for bringing it up!

**Comment by dmed256** [comment]
@amikstcyr Since I can't reproduce locally, can you try out the #472 branch?
