### ISSUE TITLE
Update documentation at libocca.org

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#474]
It's been a while since `libocca.org` was last updated. Before the `1.2.0` release, I want to have the following updated:
- Guide
    - Reorganize so it's easier to follow
    - Add `occa::forLoop` and `occa::array`
- API
    - Now that we've split the public and private API, I hope to have most if not all classes and methods documented. I want to try out Sphinx to extract comment metadata, but will fall back to manually writing it :disappointed: 

I would also like to have the examples updated so it's easier to find features :thinking:

**Comment by dmed256** [comment]
API is done through #482

**Comment by kris-rowe** [comment]
User documentation will be split into separate issues and revisited in the next release.
