### ISSUE TITLE
New caching code causes intermittent compilation failure

### ISSUE THREAD

**Issue by SFrijters** [libocca/occa#509]
After updating beyond 02d6f15f01a006357a3173197409f9714a9df1dc I've started seeing intermittent failures when compiling (at least) OpenMP kernels:

```
4: ---[ Error ]--------------------------------------------------------------------
4:     File     : /<redacted>/occa/src/occa/internal/modes/serial/device.cpp
4:     Line     : 380
4:     Function : operator()
4:     Message  : Error compiling [<redacted>], Command: [mpiicpc  mpiicpc -std=c++11<... redacted...>]
4:                Output:
4:                
4:                icpc: error #10236: File not found:  'mpiicpc'
```

I've added some `std::cout` debugging and it looks like `compilerFlags` is set via the `} else if (kernelProps.get<std::string>("compiler_flags").size()) {` branch and it sometimes (correctly) contains `-qopenmp`, but sometimes it contains `mpiicpc`. In the second case I see the error above.

Is this `kernelProps` now shared somehow in a way that it wasn't before? The commit is rather large for me to quickly make sense of.

**Comment by dmed256** [comment]
Hmm strange, I don't think I touched `kernelProps` lately but I can double check the PR. Can you send over your `make info` output even if it's redacted in some places?

**Comment by SFrijters** [comment]
I thought that there might be some issue with sharing / the closure of the new lambdas (btw, I really like the cleanliness of this implementation, it's pretty much what I had in mind, except that I don't know enough fancy C++).

```
$ make info
diff: /<redacted>/occa/include/occa/defines/compiledDefines.hpp: No such file or directory
--------------------------------
CXX            = mpiicpc
CXXFLAGS       = (empty)
CC             = mpiicc
CFLAGS         = (empty)
FC             = mpiifort
FFLAGS         = (empty)
LDFLAGS        = (empty)
--------------------------------
compiler       = $(CXX)
vendor         = INTEL
compilerFlags  =  -O3 -xHost -Wno-c++11-long-long -std=c++11 -fPIC
cCompiler      = $(CC)
cCompilerFlags =  -O3 -xHost
fCompiler      = $(FC)
fCompilerFlags =  -O3 -xHost -fPIC
flags          = 
paths          = -I/<redacted>/occa/include -I/<redacted>/occa/src -I<redacted other library inc dir> -I<redacted other library inc dir> -I/<redacted>/occa/include -I/apps/EasyBuild/software/CUDAcore/11.4.1/include -I/apps/EasyBuild/software/CUDAcore/11.4.1/include
fPaths         = -L/<redacted>/occa/lib  -I<redacted other library inc dir>  -I<redacted other library inc dir>  -I<redacted>/occa/lib/fortran/modules
sharedFlag     = -shared
pthreadFlag    = -lpthread
linkerFlags    = -lm -lrt -ldl -L/lib -lcuda -L/apps/EasyBuild/software/CUDAcore/11.4.1/lib -lOpenCL
--------------------------------
debugEnabled   = 0
checkEnabled   = 1
debugFlags     =  -g
releaseFlags   =  -O3 -xHost
picFlag        = -fPIC
--------------------------------
fortranEnabled = 0
mpiEnabled     = 1
openmpEnabled  = 0
openclEnabled  = 1
metalEnabled   = 0
cudaEnabled    = 1
hipEnabled     = 0
```
Note that I normally don't use standalone Make at all, but the CMake build. I normally have OpenMP enabled and OpenCL disabled for example.

```
$ occa env
  Basic:
    - OCCA_DIR                   : /<redacted>/occa/opt/release-intel-cuda
    - OCCA_CACHE_DIR             : /<redacted>/tmp/occa/intel64-release
    - OCCA_VERBOSE               : 1
    - OCCA_UNSAFE                : 0
  Makefile:
    - CXX                        : mpiicpc
    - CXXFLAGS                   : [NOT SET]
    - CC                         : mpiicc
    - CFLAGS                     : [NOT SET]
    - FC                         : mpiifort
    - FCFLAGS                    : [NOT SET]
    - LDFLAGS                    : [NOT SET]
  Backend Support:
    - OCCA_OPENMP_ENABLED        : 1
    - OCCA_CUDA_ENABLED          : 1
    - OCCA_HIP_ENABLED           : 0
    - OCCA_OPENCL_ENABLED        : 0
    - OCCA_METAL_ENABLED         : 0
    - OCCA_MPI_ENABLED           : 1
  Run-Time Options:
    - OCCA_CXX                   : [NOT SET]
    - OCCA_CXXFLAGS              : [NOT SET]
    - OCCA_CC                    : [NOT SET]
    - OCCA_CFLAGS                : [NOT SET]
    - OCCA_LDFLAGS               : [NOT SET]
    - OCCA_COMPILER_SHARED_FLAGS : [NOT SET]
    - OCCA_INCLUDE_PATH          : <redacted>
    - OCCA_LIBRARY_PATH          : [NOT SET]
    - OCCA_KERNEL_PATH           : <redacted>
    - OCCA_OPENCL_COMPILER_FLAGS : [NOT SET]
    - OCCA_CUDA_COMPILER         : [NOT SET]
    - OCCA_CUDA_COMPILER_FLAGS   : [NOT SET]
    - OCCA_HIP_COMPILER          : [NOT SET]
    - OCCA_HIP_COMPILER_FLAGS    : [NOT SET]
```

My environment is very tightly controlled and I've checked our calling code and it does not set/override kernelProps["compiler_flags"]  in the current build (and even when it does, it actually sets compiler flags, it doesn't put a compiler executable in there).

**Comment by dmed256** [comment]
Hmm that's so weird, we never `+=` or `command <<` in other places so I have no idea where that second `mpiicpc` could have been introduced. Is this after a clean re-compilation of OCCA?

**Comment by SFrijters** [comment]
The second `mpiicpc` comes from the `kernelProps["compiler_flags"]` somehow - some of the time it suddenly contains `mpiicpc` instead of `-qopenmp`. It's very much a clean build, and I can consistently make the program go away / appear by reverting / re-adding the caching commit. Although that doesn't preclude there being a previous issue of course that is just exposed now somehow. I can do some more digging tomorrow, but I was hoping you'd think of a good explanation so I wouldn't have to :sweat_smile:

**Comment by dmed256** [comment]
Can you try printing `outFilename` in the `openmp/utils.cpp`?

```cpp
      std::string flag = openmp::notSupported;
      ss << io::read(outFilename);
      ss >> flag;
```
&rarr;
```cpp
      const bool usingOpenMP = (lastCompilerOpenMPFlag != openmp::notSupported);
      if (usingOpenMP) {
        allKernelProps["compiler_flags"] += " " + lastCompilerOpenMPFlag;
      }
```
I wonder if it's coming from here 🤔

**Comment by SFrijters** [comment]
I think #510 fixes it.

**Comment by amikstcyr** [comment]
Well done!

**Comment by dmed256** [comment]
Closing due to the `ss` &rarr; `ss_` fixes, thank you!
