### ISSUE TITLE
Position of Dependency functions of OKL file

### ISSUE THREAD

**Issue by eswarnitk** [libocca/occa#538]
How and where to define the dependent functions of OKL kernel?

@kernel void Sample(...){
    for(.....; @outer){
    for(....; @inner){
        function1();
        .<Statements>
    }
    }
} 

Condition 1 : If we define the function1 in the same okl, then the execution is faster.
Condition 2 : Define the function1 in .hpp and include it in the .okl file, then the program runs a bit slower.
Is my understanding correct? Or Is there any other way to define the dependency functions of OKL file?

Regards,
G Eswar

**Comment by kris-rowe** [comment]
Either approach should work. For example,  [this OKL kernel](https://github.com/libocca/occa/blob/45462a3d62160a82009542ff7806ed86553527f8/examples/cpp/01_add_vectors/addVectors.okl) could be rewritten as
```
float addFloats(const float a,const float b)
{
  return (a+b);
}

@kernel void addVectors(const int entries,
                        const float *a,
                        const float *b,
                        float *ab) {
  for (int i = 0; i < entries; ++i; @tile(4, @outer, @inner)) {
    // ab[i] = a[i] + b[i];
    ab[i] = addFloats(a[i],b[i]);
  }
}
```
Alternatively, the `addFloats` function could be defined in a header file,
```
#include "addFloats.hpp"

@kernel void addVectors(const int entries,
                        const float *a,
                        const float *b,
                        float *ab) {
  for (int i = 0; i < entries; ++i; @tile(4, @outer, @inner)) {
    // ab[i] = a[i] + b[i];
    ab[i] = addFloats(a[i],b[i]);
  }
}
```
which requires an `occa::json` object to be passed to the kernel constructor in the application code
```
occa::json kernel_properties;
kernel_properties["includes"]="addFloats.hpp"

occa::kernel vector_add = device.buildKernel("addVectors.okl","addVectors",kernel_properties);
```

**Comment by noelchalmers** [comment]
I don't think theres a performance difference for either of the 2 cases. 

Some GPU codes can see a slow down when linking device functions that were compiled in different translation units, but that isn't what's happening here.
