### ISSUE TITLE
Restore CUDA/OpenCL kernel source support

### ISSUE THREAD

**Issue by lferraro** [libocca/occa#55]
Hi everybody. 

Waiting for the release of libocca 1.0, I strongly suggest to add support for CUDA/OpenCL kernel source in CUDA/OpenCL OCCA mode: this would be of great advantage when porting an existent CUDA accelerated program with OCCA. 

What I suggest is:
1. add a NativeCUDA, NativeOpenCL mode for kernel build in order to use already existent CUDA/OpenCL source code kernels (to use only with CUDA and OpenCL OCCA mode of course).
a) please, remove any dummy argument in order to call the CUDA/OpenCL kernel (see original implementation in the "master" branch of libocca)
b) use a unique semantic for formal parameters of the setWorkingDims method of the kernel class, for example: CUDA way (dims, gridOfBlocks, blockDims) or OpenCL way (dims, gridOfElements, blockDims)

Thank you for you great work and support

Luca Ferraro

**Comment by dmed256** [comment]
Commit 7a92d91 adds this feature

The format is

```cpp
occa::device device("mode: 'CUDA', OKL: false");
```

or on a kernel-by-kernel basis

```cpp
occa::kernel addVectors = device.buildKernel("addVectors.okl",
                                             "addVectors",
                                             "OKL: false");
```

This works for OpenCL and CUDA, will add the same feature for Serial/OpenMP

The API for setting the dimensions of the kernel also changed

```cpp
addVectors.setRunDims((entries + 15)/16, 16)
```

or

```cpp
occa::dim inner(16, 16);
occa::dim outer((X + 15)/16, (Y + 15)/16);
addVectors.setRunDims(outer, inner);
```

**Comment by dmed256** [comment]
@lferraro The format for passing properties from `device` to the `memory` it allocates and `kernels` it builds

To pass properties from a `device` to all of its allocated `memory`:

```c++
occa::device device("mode: 'CUDA', memory: { managed: true }");
```

To pass properties from a `device` to all of its built `kernels`:

```c++
occa::device device("mode: 'CUDA', kernel: { OKL: false }");
```
