### ISSUE TITLE
Caching mechanism is broken for findCompilerVendor.cpp

### ISSUE THREAD

**Issue by Siebren** [libocca/occa#553]
The compilerVendorTest is stored in the occa cache:
https://github.com/libocca/occa/blob/a14fcd404a436fb8f6175742e591f2febbf533a0/src/occa/internal/utils/sys.cpp#L724-L735
But `io::cacheFileIsComplete` to check if it is already cached is a special function, in that it is only called/used from this one place.

https://github.com/libocca/occa/blob/a14fcd404a436fb8f6175742e591f2febbf533a0/src/occa/internal/io/cache.cpp#L88-L95
It still looks for the `.success` pattern that got removed in #505. So it will not ever find a `.success` file/directory.

This appears to result in the findCompilerVendor.cpp function always getting recompiled and occa always attempting to write it into the cache, even though the output may already be present.

**Comment by kris-rowe** [comment]
Which OS, compiler, occa mode/backend, and type of filesystem are you using when you observe this?

**Comment by Siebren** [comment]
I see this with RedHat Linux 8.3, icc (ICC) 19.0.1.144 20181018, OpenMP, and an XFS filesystem.

With how I understand this issue, I expect that none of the information above will be relevant, but rather that this issue is present in all cases that go through this function. I think the issue is that the logic of appending a ".success/" to a filename to be searched is no longer valid since #505.

**Comment by Siebren** [comment]
Two simple ways to check if you are affected by this issue is to run any occa job that will compile the findCompilerVendor.cpp function. Then go into your OCCA_CACHE_DIR, and write-protect the output file belonging to that function (e.g. chmod u-w output), or note the modification time of that file.

Run the same job again. If you protected that file, you will get an error that occa failed to open the file for writing. Or if you did not write protect the file, you can inspect the modification time of the file, you will see it got updated.
Write protecting any other output or binary file in the caching directory does not cause issues for me.

**Comment by kris-rowe** [comment]
Fixed by #554
