### ISSUE TITLE
Provide costructors for occa::memory objects with offsets

### ISSUE THREAD

**Issue by lferraro** [libocca/occa#56]
In many situations, we need to pass subset of memory buffers to the kernel, for example when working with many streams (in order to implement a pipe-line to process a big buffer in chunks with the same kernel) you require that the kernel operates on different portions of a memory buffer.

```
for (int i=0; i<nchunks; ++i) {
  size_t starting_index = i * chunksize;
  // stuff like device.setStream(.......)
  // asynch copy stuff for buffers from base + starting_index of size chunksize
  kernel( occa::memory(bufA, start_index), occa::memory(bufB, start_index) );
  // asynch copy back stuff
}
```

What I suggest is to provide a simple way to create occa:memory objects from other existing occa::memory, using an offset: this is a "must have" in all situations where you need to process subsection of a occa::memory buffer with a kernel, for example when using multiple streams for
processing a buffer in chunks (see attached example).

You can go through a operator+ or a copy costructor (or both), so to let user write something like that:
```
// modified source from the master branch of libocca
template<> memory_t<CUDA>::memory_t(const memory_t<CUDA> &m, const
uintptr_t offset) {
  *this =m;
  handle = new CUdeviceptr;
  CUdeviceptr base = (CUdeviceptr)m.handle; (CUdeviceptr*)handle =
base + offset;
}
```
For OpenCL we can use subbuffers.

We must grant memory resources will not to be destroyed when the newly shifted memory object goes out of scope.

**Comment by dmed256** [comment]
Added in a244b01
