### ISSUE TITLE
Add support to use __constant in GPU modes

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#57]
Try out the following to see if we can add `__constant` to work on native CUDA kernels.
Manually put the constant variable/array with a name in the kernel file

```cuda
__constant float myVar;
__constant float myArray[10];
```

Compile kernel

```cpp
occa::kernel foo = device.buildKernel('foo.cu', 'foo')
```

Use an OCCA helper method to initialize the constant​ value. The 'extra work' part is keeping track of the variable name and size outside of the kernel:

```cpp
float myVar = 10;
float *myArray = new float[10];
​// Initialize myArray​

occa::cuda::initConstantMemory(foo, 'myVar'  , &myVar , sizeof(float));
occa::cuda::initConstantMemory(foo, 'myArray', myArray, 10 * sizeof(float));
```

**Comment by lferraro** [comment]
It sounds good to me. This approach can be extened to occa::opencl as well.

**Comment by dmed256** [comment]
Haven't heard about leveraging this for a while so I'm closing it. We can open it back up if there is a good API suggestion on how to add constant memory support to OCCA/OKL :)
