### ISSUE TITLE
device::free() failure in CUDA mode

### ISSUE THREAD

**Issue by lferraro** [libocca/occa#58]
There's a problem with resource deallocation when using OCCA in CUDA native mode.

    File     : <stripped>/occa/src/modes/cuda/kernel.cpp
    Function : free
    Line     : 260
    Message  : Kernel (addVectors) : Unloading Module
    Error   : CUDA Error [ 709 ]: CUDA_ERROR_CONTEXT_IS_DESTROYED
    Stack    :
      6 occa::cuda::error(cudaError_enum, std::string const&, std::string const&, int, std::string const&)
      5 occa::cuda::kernel::free()
      4 occa::kernel::removeKHandleRef()
      3 ./main()
      2 /lib64/libc.so.6(__libc_start_main+0xf5)
      1 ./main()

I attach a simple diff file to apply to examples/nativeAddVectors which should reproduce the problem.

Thank you for your precious work,

[nativeAddVectors.diff.zip](https://github.com/libocca/occa/files/905496/nativeAddVectors.diff.zip)

**Comment by dmed256** [comment]
Whoops, I didn't think about the kernel and memory depending on the device (due to the context)
I'll have the reference counts affect the device as well, that way the device will get freed after all kernels and memory objects

Thanks for finding more bugs, appreciate it!

**Comment by dmed256** [comment]
I pushed the fix, can you try it out?

**Comment by dmed256** [comment]
Ok, kernels and memory will free the device if they're the last reference to it :)
