### ISSUE TITLE
Add method to get current stream object

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#597]
This can be useful coupling occa application codes with other device accelerated libs.

**Comment by stgeke** [comment]
Currently there is no way to access the member cuStream of occa::cuda::stream. It's not part of the API.

**Comment by kris-rowe** [comment]
You are correct. We will need to add a function to the frontend device API to make this happen.

**Comment by SFrijters** [comment]
I would also be very interested in a principled way to get this out. We currently use a hack similar to https://github.com/libocca/occa/pull/606 to punch through the abstractions and pull out a stream.

**Comment by deukhyun-cha** [comment]
I second that this is definitely needed to utilize 3rdparty libraries with APIs expecting native device data pointers. To the @SFrijters point, I am wondering if it would be a good idea/possible to provide a general API which returns native pointer (void*) of the actual data from occaType (although not all occaType has it). I think this could be useful especially for types like occaStream or occaMemory to communicate with 3rdparty libraries designed for a certain device target/platform. Just a thought.
