### ISSUE TITLE
CMake options should be prefixed with `OCCA` to avoid name conflicts when used in bigger projects

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#612]

**Comment by kris-rowe** [comment]
Agreed. Good call.

**Comment by kris-rowe** [comment]
> Hello, I'm interested in helping with this! Wanted try my hand and learn as I go! Is this up for grabs? I saw that the last activity was last month

We are always happy to welcome new contributors. Feel free to tackle this issue.

Whenever you create a pull-request for, please have it target the [development branch](https://github.com/libocca/occa/tree/development). 
If you would like some early feedback on your PR before it is finished, you can open it early and mark it as a draft.
