### ISSUE TITLE
Errors in examples midgTest & mandelbulb

### ISSUE THREAD

**Issue by cbjcbj** [libocca/occa#62]
Hi, I use branch 1.0. When I test examples I get errors. 
In `midgTest`, it says could not find function [midg] in file `midg.okl`.
In `mandelbulb`, it says no `setupAide.hpp`. 
Thank you.

**Comment by dmed256** [comment]
Sorry about that, the examples were out of date
I updated the examples for 1.0 except
- addVectors/f90
- addVectors/jl
- addVectors/py

**Comment by dmed256** [comment]
Forgot to add, midgTest isn't in 1.0
Feel free to re-open the issue if you're having issues :)
