### ISSUE TITLE
 math functions for vectors (floatn)

### ISSUE THREAD

**Issue by dshawul** [libocca/occa#63]
Concerning vector data types.

a) The opencl floatn vectors support math functions such as sin, cos etc, but occa's support in non-opencl mode lacks that. 

b) Support for all float-n types such as float3, float6, float9 which can be used  to represent vector, symmetric tensor and tensor.

**Comment by dmed256** [comment]
Only kept float2 and float4 (same with other pod types)
OpenCL and CUDA alias float3 as float4 for performance reasons
