### ISSUE TITLE
For consistency `memory::copyFrom` and `memory::copyTo` should be `dtype` aware

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#686]
Similar to `memory::slice`.

**Comment by noelchalmers** [comment]
In what sense are they not agnostic? Those routines just take byte counts as inputs: https://github.com/libocca/occa/blob/main/src/core/memory.cpp#L188

**Comment by noelchalmers** [comment]
Ooh, you want them to actively _use_ the dtype. Sorry, title gave a me a different impression.
