### ISSUE TITLE
[Parser] Constant expression "1e-..." truncated to "1"

### ISSUE THREAD

**Issue by camierjs** [libocca/occa#71]
Found in `laghos/kernels/cpu/quadratureData.okl` when `(cNorm > 1e-16)` and `(maxNorm > 1e-16)` lines 370 and 377

**Comment by dmed256** [comment]
Nice find! I'll check it out.
Glad I'm redoing the parser ;)

**Comment by dmed256** [comment]
Fixed and added test for it:
https://github.com/libocca/occa/blob/1.0/parser_sandbox/tests/testPrimitive.cpp#L66
