### ISSUE TITLE
Allow return statements

### ISSUE THREAD

**Issue by camierjs** [libocca/occa#83]
Would it be possible to allow a return statement (return 0 on success, otherwise failure)?

**Comment by dmed256** [comment]
Might end up being something like:
```cpp
void *value = myKernel(a, b, c);
int value   = myKernel(a, b, c).to<int>();
int value   = myKernel(a, b, c);
```
with the C version like
```c
occaKernelRun(myKernel,
              a, b, c);
occaKernelGetReturnValue(myKernel, &value)
```

**Comment by camierjs** [comment]
Fine for me!

**Comment by dmed256** [comment]
Closing since the user can pass an argument to set the error value if needed. It would be nice to support it out of the box, but it'll be quite a bit of work to support unfortunately :disappointed:
