### ISSUE TITLE
Use compiler-defined macros in the preprocessor

### ISSUE THREAD

**Issue by camierjs** [libocca/occa#87]
Would it be possible to keep these directives down to the kernel?
*just asking*

**Comment by dmed256** [comment]
There only directives that will live through the preprocessing stage are:
```cpp
#pragma occa @...
```
as attributes, or regular pragmas
```cpp
#pragma ...
```
Is that what you're looking for?

**Comment by camierjs** [comment]
hum, I was more thinking of [http://en.cppreference.com/w/c/preprocessor/conditional](url)

**Comment by dmed256** [comment]
Oh, the preprocessor handles them since they are in the source code. Is there a reason to keep them around?

**Comment by camierjs** [comment]
Well, even if they are in the OKL source code, if I do something like:
 `
#ifdef __NVCC__ 
{CUDA debug stuff}
#else 
{other host debug}
#endif
`
then the parser only selects the `{other host debug}` statements.

**Comment by dmed256** [comment]
Oh, I'm planning on picking up the compiler defines. I have a TODO in the preprocessor constructor to remind me

**Comment by dmed256** [comment]
In f9f433f968d1602bfc7eca9d9926a8f5651139d5
```cpp
#pragma occa @tile(16, @Inner, @outer)
for (int i = 0; i < N; ++i) {
}
```
↓
```cpp
for (int i = 0; i < N; ++i; @tile(16, @inner, @outer)) {
}
```
Still missing compiler-dependent defines, like `__NVCC__`
