### ISSUE TITLE
[cuda] compiler default options

### ISSUE THREAD

**Issue by camierjs** [libocca/occa#89]
compilerFlags for CUDA are set with -Xptxas -v,-dlcm=cg

- can the verbose option be added accordingly to occaSetVerboseCompilation argument?
- disabling the L1 cache should however be removed

**Comment by dmed256** [comment]
I'll remove those default flags, good catch
Also, setting `OCCA_VERBOSE=1` as an environment variable should produce the same result as manually setting `occaSetVerboseCompilation`

**Comment by dmed256** [comment]
Those compiler flags are only to [check memory usage](https://github.com/libocca/occa/blob/master/src/modes/cuda/kernel.cpp#L100-L128) (shared, register, register spilling, etc)
The compilation happens [right after](https://github.com/libocca/occa/blob/master/src/modes/cuda/kernel.cpp#L130-L139)
