### ISSUE TITLE
[okl] outer w/o inner

### ISSUE THREAD

**Issue by camierjs** [libocca/occa#90]
kernel with outer for-loop seem to require at least one inner-loop, could it be added while parsed?

**Comment by dmed256** [comment]
The kernels are going to end up being runtime compiled functions, using the backend mode only if outer/inner is specified

For serial, OpenMP, and threads modes, inner will be optional and ignored. Inner will still be required for the GPU modes

**Comment by camierjs** [comment]
Sounds good, will this come with the new parser, or future developments?

**Comment by dmed256** [comment]
New parser, adding it to the current one will end up being thrown away soon :(

**Comment by pdhahn** [comment]
For simple situations, you can just use tile(N) instead of outer+inner! I use it a lot.

**Comment by dmed256** [comment]
I'll add an option to handle cases where the loops don't match the loop bounds with blocking perfectly
Maybe something like
```cpp
for (int i = 0; i < 7; ++i; @tile(16, guard=true)) {
    ...
}
```
which would turn into
```cpp
for (int i = 0; i < 7; ++i) {
    if (i < 7) {
        ...
    }
}
```

**Comment by dmed256** [comment]
#92

**Comment by dmed256** [comment]
Adding the kernel property
```cpp
kernelProps["okl/validate"] = false;
```
will avoid doing OKL validation checks

⚠️ This should allow not having to use `@inner` loops, but **use at your own risk** ⚠️
