### ISSUE TITLE
command line access of OCCA version

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#91]
(Cannot find this feature anywhere. If it exists, please advise.)

Please add an option to the 'occa' program to print the OCCA version. Something like "--version", say.

As OCCA continues to change over time, this would be very helpful.

**Comment by pdhahn** [comment]
But yes, in addition, it might also be nice if the OCCA version were _directly_ accessible in user runtime code that uses OCCA. Maybe via a predefined prepro constant _OCCA_VERSION_ generated by the OCCA build process into include/occa/occa.h -- i.e., something akin to __GNUC__, __GNUC_MINOR__, and __GNUC_PATCHLEVEL__, when those are typically combined into a single integer like _GCC_VERSION_.

It might even also be useful if such a predefined constant were automatically available in _.okl_ files, defined during processing by the parser.

But even if none of this were automatically available, things can be arranged on the user's side of the fence to (say) embed the version returned by the requested command line option into the make system for the user's own code. Such would be the user's responsibility. That would be fine for me.

**Comment by dmed256** [comment]
Good idea!
I added a few macros I will update as version numbers increase ([occa/defines.hpp](https://github.com/libocca/occa/blob/master/include/occa/defines.hpp#L272-L282))
```cpp
#define OCCA_MAJOR_VERSION 1
#define OCCA_MINOR_VERSION 0
#define OCCA_PATCH_VERSION 0
#define OCCA_VERSION       10000
#define OCCA_VERSION_STR   "1.0.0"

#define OKL_MAJOR_VERSION 0
#define OKL_MINOR_VERSION 2
#define OKL_PATCH_VERSION 0
#define OKL_VERSION       200
#define OKL_VERSION_STR   "0.2.0"
```
and added it to `./bin/occa` 
```bash
> occa
Incorrect number of arguments

Usage: occa COMMAND

Can be used to display information of cache kernels.

Commands:
  autocomplete    Prints shell functions to autocomplete occa
                  commands and arguments
  cache           Cache kernels
  clear           Clears cached files and cache locks
  env             Print environment variables used in OCCA
  info            Prints information about available OCCA modes
  version         Prints OCCA library version

Arguments:
  COMMAND    Command to run

[~/git/night]
> occa version
1.0.0
[~/git/night]
> occa version --okl
0.2.0
```
