### ISSUE TITLE
Add guard to @.tile

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#92]
It's a pain to add a check to `@tile(N)`, have an option to add an `if()` check. Whether it's the default is still up in the air

Maybe something like
```cpp
for (int i = 0; i < 7; ++i; @tile(16, guard=true)) {
    ...
}
```
which would turn into
```cpp
for (int i = 0; i < 7; ++i) {
    if (i < 7) {
        ...
    }
}
```

**Comment by pdhahn** [comment]
In pre-occa1, I have become accustomed to just always add a guard statement explicitly, right under the for-tile statement, thus:
```
for (int i = 0; i < 7; ++i; tile(16)) {
    if ( !(i < 7) ) continue;
    ...
}
```

**Comment by dmed256** [comment]
It's still required, but it would be nice to have a way to automatically add it

**Comment by pdhahn** [comment]
Yes indeed. :-)

**Comment by dmed256** [comment]
Just added `@tile(..., safe=true)`
```cpp
for (int i = 0; i < N; ++i; @tile(16, @outer, @inner, safe=true)) {
  int x;
}
```
↓
```cpp
for (int _occa_tiled_i = 0; occa_tiled_i < N; _occa_tiled_i += (16)) {
  for (int i = _occa_tiled_i; i < (_occa_tiled_i + 16); ++i) {
    if (i < N) {
      int x;
    }
  }
}
```
