### ISSUE TITLE
Typo in scripts/Makefile

### ISSUE THREAD

**Issue by v-dobrev** [libocca/occa#94]
In the following `ifndef` should be `ifdef`:

https://github.com/libocca/occa/blob/48cf18af79da6463074b8757b923f7ad1e6a5174/scripts/Makefile#L125-L129

It can be simplified to
```gmake
CC ?= gcc
```

And, in fact, make (at least GNU make) always defines `CC` (as `cc` usually), so you don't need to do anything.

**Comment by dmed256** [comment]
Ah nice catch, can you make a PR with the change?
Or I can fix it tonight

**Comment by dmed256** [comment]
Fixed in 197e34d
